### ISSUE TITLE
Double orders when switching to v4.1.3 or v4.2.0

### ISSUE THREAD

**Issue by RVanDamage** [mollie/PrestaShop#284] opened 2021-01-26 20:53 UTC
### Expected behavior
No double orders when activating Mollie v4.1.3 or v4.2.0

### Actual behavior
Double orders when either v4.1.3 or v4.2.0 is activated

### Steps to reproduce the behavior
Disabled Mollie v4.x and reinstalled v3.5.5

### Details
Our customer store was running on Presta 1.7.6.2 and Mollie v3.5.5
We upgrade store (on dev location too) from 1.7.6.2 to 1.7.6.9
After updating Mollie module from v3.5.5 to v4.1.3 we noticed a lot of double orders being displayed
We deleted Mollie completely (including checking left overs in DB tables ps_module and ps_hook_module)
Reinstalled Mollie module but this time v4.2.0, reconfigured whole module because settings were gone
Again we see double orders
Deleted Mollie completely again, and reinstalled Mollie v3.5.5, double orders are gone.
Check my screenshots.
<img width="866" alt="Schermafbeelding 2021-01-26 om 21 50 48" src="https://user-images.githubusercontent.com/68848292/105903938-d09b7100-6020-11eb-8275-f4fcaf812a09.png">
<img width="911" alt="Schermafbeelding 2021-01-26 om 20 11 05" src="https://user-images.githubusercontent.com/68848292/105903946-d2fdcb00-6020-11eb-85fb-c7babc301ef3.png">

**Comment by Saimis777** [comment] 2021-01-27 09:05
Hello, and thank you for your message!

I will check with the development team regarding this report, and will get back to you as soon as possible!

Thank you for your patience.

--
Best regards,
Invertus Support team

**Comment by RVanDamage** [comment] 2021-01-27 09:29
Hi @Saimis777,

Thanks for your quick reply.

A duplicated ID is something that physically should not be possible (database should not allow a duplicate ID), maybe just some display error...

**Comment by Saimis777** [comment] 2021-01-28 09:28
@RVanDamage hey again,

Would you be able to send us front/back office/FTP details to support@invertus.eu for further investigation? Or more information about the issue? As without further details we can't really determine what the issue is, as we didn't have this issue before.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by RVanDamage** [comment] 2021-01-28 13:28
Hi @Saimis777,

Thanks, I just send them the credentials  (front/back office/FTP) for one of our dev environments.
Already enabled the Mollie module, so they should see those order duplicates.
As soon Mollie module is disabled (try it) the order duplicates are gone.

**Comment by Saimis777** [comment] 2021-01-28 13:41
Thank you, I've received your email.

Will update you regarding the process!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-01-28 15:35
@RVanDamage
 
One of the main reasons we refactored how order is create because of the reason that a lot of merchants just like in this case likes to change order_reference logic, and because a lot of orders were canceled and they ask mollie for order reference before they can create payment they got duplicated, as you can see in the image after using 3.3.5 module it finds more then 1 order_reference that has the same reference, this shouldn’t happen with new orders when using new 4.2.1 version, but the old ones will show it because they were created using 3.3.5 module, you could delete them from mollie_payment table where order_id is empty if you don't want to see them.

![image](https://user-images.githubusercontent.com/75423142/106160064-1cb7f400-618e-11eb-8eb1-86d41b4169e5.png)

The fix for this issue will be released in 4.3.0 version, but if you want, you can currently change - mollie.php line : 1009

Change this code:

if (isset($params['join'])) {
   $params['join'] .= ' LEFT JOIN `' . _DB_PREFIX_ . 'mollie_payments` mol ON mol.`order_reference` = a.`reference` 
   AND mol.`cart_id` = a.`id_cart`';
}


To this:

if (isset($params['join'])) {
   $params['join'] .= ' LEFT JOIN `' . _DB_PREFIX_ . 'mollie_payments` mol ON mol.`order_reference` = a.`reference` 
   AND mol.`cart_id` = a.`id_cart` AND mol.order_id > 0';
}




Let me know if you need any other assistance!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-01-29 10:12
Hello,

As this issue was provided with a solution, and the fix will be released in 4.3.0 version, I will close this issue.

Please let me know if you will encounter any further issues or bugs, we are here to help!

--
Best regards,
Invertus Support team

**Closed by Saimis777** 2021-01-29 10:12 UTC
