### ISSUE TITLE
Cannot add product with combinations to cart

### ISSUE THREAD

**Issue by EddyWebdelta** [mollie/PrestaShop#978] opened 2024-10-02 14:50 UTC
When I select some combinations. We got error:
NL: U hebt al de maximale hoeveelheid dat beschikbaar is voor dit product.
ENG: You already have the maximum quantity available for this product

When I disable Mollie module, product is added to cart.

Mollie 6.2.3 (also tried 6.2.2)
Prestashop 8.2.0
PHP 8.2

Kind regards,
Eddy

**Comment by justelis22** [comment] 2024-10-03 06:42
Hi there,

We will check this issue and I will get back to you as soon as more details.

Thank you for your patience!

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2024-10-04 09:01
Hi there @EddyWebdelta,

Before we begin to dig in, I can see that you are using an unsupported PHP version by PrestaShop:
![image](https://github.com/user-attachments/assets/9389909c-48ab-48f2-b007-ef841852520b)

We have checked this issue and tried to recreate it locally on our environments, however, everything seems to be working fine, but we were not able to prompt this issue.

Can you please let me know how the issue can be recreated? Exact steps would be needed.

Please attach some screenshots or a video recording of the error, and error logs from the module logs tab.

Thanks!

Best Regards,
Invertus Support team.

**Comment by EddyWebdelta** [comment] 2024-10-08 07:00
Hi, yes, we tested it in PHP7.4, 8.0 and 8.1 but unfortunately it still gives same errors.
It only happens with products with a lot of combinations. (480 in our case). Not with two combinations.

When Mollie module is enabled and we try to add product with lot of combinations in cart. Error is:
NL: U hebt al de maximale hoeveelheid dat beschikbaar is voor dit product.
ENG: You already have the maximum quantity available for this product.

When we disable Mollie module and put product in our cart, then activate Mollie module again. When we want to proceed to checkout, we are redirected to /authentication, we got error:
NL: De klant moet aangemeld zijn om een item met abonnement aan te kopen.
ENG: Customer must be logged in to buy subscription item.

See screendumps.
![Authentication - deridder webdelta2 nl](https://github.com/user-attachments/assets/35de7e9f-6300-47c3-89cf-16a509b0fcf4)
![DRAAKJE 19 PERS  KIES SMAAK EN KLEUR - deridder webdelta2 nl](https://github.com/user-attachments/assets/62796334-09fa-4ae2-a0fc-c7349dea1978)

**Comment by justelis22** [comment] 2024-10-10 07:16
Hi there @EddyWebdelta,

Could you please clarify if this issue occurs when trying to add the first product to the cart, or do you get it when adding more than one?
As per this issue - https://github.com/mollie/PrestaShop/issues/983 only one subscription can be created per order.

Or are you not using subscriptions at all?

Best Regards,
Invertus Support team.

**Comment by EddyWebdelta** [comment] 2024-10-11 06:29
We don't use subscriptions at all.

**Comment by justelis22** [comment] 2024-10-11 13:42
Hi there,

We have checked this issue and tried to recreate it locally on our environments, however, everything seems to be working fine, but we were not able to prompt this issue.

That being said, we will need access to your shop to debug the issue. Can you provide the Back Office and FTP credentials?
If you have a development environment, that would be even better. That way, we can work on the issue without disturbing the live store.

You can add the credentials here - https://privatebin.net/ and share the link with us via email support@invertus.eu.

Thanks!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2024-10-16 07:35
@EddyWebdelta Hey there,

I have replied to you via email.

It seems like there is an issue with attributes, your color attribute got assigned as the Mollie Subscription attribute.

We are not sure why this could have happened, perhaps it was duplicated on the development store.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2024-10-16 08:48
Another update:
The issue is most likely related to editing the Mollie group attribute and adding new attributes inside.

There are two ways to fix this issue:

- Recreate this group attribute and reset the module.
- Delete subscription-related values from the database and reset the module.

From our side, we will add additional validations to prevent from this issue happening.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2024-10-17 06:22
Resolved by the merchant, confirmed via email.

As mentioned above, color and Mollie subscriptions had the same attribute ID.

We will add some additional validations to prevent this in the future.

**Closed by justelis22** 2024-10-17 06:22 UTC
