### ISSUE TITLE
Prestashop 1.7.7 error

### ISSUE THREAD

**Issue by jacob-v-dam** [mollie/PrestaShop#252] opened 2020-12-03 10:49 UTC
### Expected behavior
Not getting a 500 error

### Actual behavior
Run the webshop and you get this error:
Compile Error: Declaration of Mollie::getContainer($id = false) must be compatible with ModuleCore::getContainer(): Symfony\Component\DependencyInjection\ContainerInterface

[Symfony\Component\Debug\Exception\FatalErrorException 0]

### Steps to reproduce the behavior
Install mollie 4.1.1 and prestashop 1.7.7

### Environment
* PrestaShop version: 1.7.7.0
* Mollie module version: 4.1.1
* PHP version: 7.2

**Comment by Saimis777** [comment] 2020-12-03 15:01
Hey, thanks for your message.

We've registered the error, and passed it to our engineers, and will update you on this thread.

--
Best Regards
Invertus Support Team

**Comment by waschier-design** [comment] 2020-12-03 15:30
Same error here...
Mollie not compatible with 1.7.7
Please fix

**Comment by Vincent11110** [comment] 2020-12-03 17:49
Same here as well

Prestashop version: 1.7.7.0
Mollie module version 4.1.1
PHP version 7.3

**Comment by JeffreyDracoon** [comment] 2020-12-03 20:15
Same problem here

**Comment by wilva** [comment] 2020-12-04 12:35
Another one with the same problem.

**Comment by Saimis777** [comment] 2020-12-04 17:40
Thank you all for using Mollie module, and for informing us about this issue, we currently have our developers working on the fix, please follow this thread for updates, as soon as I receive further information, I will update it on this thread! Thank you!

--
Best regards
Invertus Support team

**Comment by Alphabyte59** [comment] 2020-12-05 18:31
Downgrading to 3.5.5 (https://github.com/mollie/PrestaShop/releases/tag/3.5.5) will fix this problem. If you can't be bothered downgrading your PrestaShop again and can't wait a couple of days until they come up with a fix, just use 3.5.5 if you can.

**Comment by Toyboy125** [comment] 2020-12-06 17:52
Same error here...
Mollie not compatible with 1.7.7

**Comment by RobMeerwijk** [comment] 2020-12-06 23:54
Same here, php 7.3 mollie 4.1.1 presta 1.7.7

**Comment by Saimis777** [comment] 2020-12-07 11:43
Thank you all for your messages, we're still working o resolving this, will update on the situation in this thread!

--
Best regards
Invertus Support team

**Comment by qualityangel** [comment] 2020-12-07 13:31
Hope it comes soon, now there is no payment module working in the store. Had hoped that you guys had it ready before the 1.7.7.0 release, there was already 2 rc releases.

**Comment by alekshnl** [comment] 2020-12-07 14:36
Thanks for the update! Hope you guys can fix it soon, my shop can't accept any payments at the moment. It's frustrating. Good luck fixing it, please keep us posted!

**Comment by caglarutkuguler** [comment] 2020-12-07 19:35
Same error here. No solution, yet? Downgraded file cannot be installed on Prestashop 1.7.7 either.

**Comment by Saimis777** [comment] 2020-12-08 09:03
Hello, unfortunately no updates yet, but as soon as I receive any updates at all, I will definitely post it here, and keep you all updated!

Thank you for your patience.

--
Best regards
Invvertus Support team

**Comment by iwan75** [comment] 2020-12-08 09:53
I don't use Mollie and get the Same Error. Can i disable it on the DB? It looks like it's active on my system by mistake.

**Comment by jacob-v-dam** [comment] 2020-12-08 10:05
@iwan75 yes you can try. In `ps_module` you can change `active` to `0`, or just remove it but this could cause problems with  any hooks.

I found a real quick and dirty solution to fix this problem:

- Rename `getContainer` to `getModuleContainer` on line 195 in the file `mollie.php`
- Find all occurrences in the file `mollie.php` which call `$this->getContainer` and rename them to `$this->getModuleContainer`
- In all other files find `$this->module->getContainer` and rename this to `$this->module->getModuleContainer`

I'm using this solution for a couple of days and it is working fine, since I'm receiving payments. I did not share this solution before I was sure that it would work.

**Comment by iwan75** [comment] 2020-12-08 10:17
> * getContainer

Thank You :-) i just found another solution. I have renamed the Folder "mollie" to "mollie-".
Now my System works fine :-)

Looks like a Workaround for People don't need Mollie.

**Comment by Saimis777** [comment] 2020-12-08 10:22
Also I would like to note that today we have a dedicated developer working on this case whole day today, so there will be an update in the evening, stay tuned, and thank you again for your patience!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2020-12-08 16:14
Update:

Currently our team knows all the main bug fixes that needs to be implemented.

Tomorrow testing of the implementations will commence.

So most likely all the fixes will be implemented, and fully tested within tomorrow.

We are very thankful for your patience, and your feedback is greatly appreciated regarding anything you notice with the new release!

--
Best regards,
Invertus Support team

**Comment by alekshnl** [comment] 2020-12-08 16:15
Great news, thank you so much for the effort today!

**Comment by JeffreyDracoon** [comment] 2020-12-09 17:00
any news?

**Comment by Maz-Invertus** [comment] 2020-12-09 17:23
Hi Everyone!

Despite of all the concentration and prioritisation of this issue our QA team found few critical issues:
- Credit card payment: $form.submit() doesn't work as expected.
- Order BO add new order checkbox doesn't appear.

We will continue working on these remaining issues tomorrow and will update you in this thread. Our team is expecting to make the 4.1.2 release tomorrow if no critical issues occurs.

Please follow this thread.
Thank you for your patience and input to the Mollie community.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2020-12-10 08:25
Hello community,

The current situation shows that the bug's that we've encountered are being fixed as we speak, and it will immediately be passed to our QA team for further testing, if no critical issues occur, we are hoping to release it today, however if any further bugs will be found, we will definitely update it in this thread. 

I fully understand how this affects your e-commerce shops, and I am sorry for the caused inconveniences, but I can assure you this case is our no.1 priority at the moment, and we have all possible hands on deck working on it, to get it resolved ASAP.

Please follow this thread.
Your patience is greatly appreciated!

--
Best regards,
Invertus Support team

**Comment by alekshnl** [comment] 2020-12-10 14:06
> Hello community,
> 
> The current situation shows that the bug's that we've encountered are being fixed as we speak, and it will immediately be passed to our QA team for further testing, if no critical issues occur, we are hoping to release it today, however if any further bugs will be found, we will definitely update it in this thread.
> 
> I fully understand how this affects your e-commerce shops, and I am sorry for the caused inconveniences, but I can assure you this case is our no.1 priority at the moment, and we have all possible hands on deck working on it, to get it resolved ASAP.
> 
> Please follow this thread.
> Your patience is greatly appreciated!
> 
> --
> Best regards,
> Invertus Support team

Thx, appreciate the status-update. Good luck!

**Comment by qualityangel** [comment] 2020-12-10 14:59
We have a temporary solution so,  i can get payments done by my customers. Well i hope you all learned from it, and in the future the update will come faster, as i said earlier the beta and rc1 and 2 were there already months ago.

I really like the freq of updates on the situation, thank you for that!

**Comment by Maz-Invertus** [comment] 2020-12-10 17:20
Hi Everyone!

Thank you for your patience! 
Finally we have the result - the latest release with PrestaShop 1.7.7 compatibility: https://github.com/mollie/PrestaShop/releases/tag/4.1.2

Please have a look and share the feedback with us. If any issue is found, please raise a separate issue that we could act accordingly.
We are going to close this issue tomorrow as it has been already solved in the latest release.

Thank you for being and active Mollie community member.
--
Best regards,
Invertus Support team

**Closed** 2020-12-11 08:02 UTC
