### ISSUE TITLE
No connection with mollie ?

### ISSUE THREAD

**Issue by Huisdierdirect** [mollie/PrestaShop#73] opened 2018-10-27 11:17 UTC
I had several complaints from customers that they can not see any of the payment methodes. 
They all get a message that there has been an error during the payment session.

This message will appear when the payment methodes can not be loaded in the mollie module.

When i checked this myself on the frontend, I had no problems and could make a payment.
Still, customers have send me e-mails and screenshots of above mentioned error message.
They could not complete their order.

Only yesterday I opened the mollie module and saw that the payment methodes could not be loaded.
Nothing was changed on any of the input I have made previously. 
It seems that now and then the connection with mollie is lost.
After a while the connection was established and the payment methodes appeared, but still the customers could not make a payment. 
I however saw all the payment methodes on the frontend.

I have cleared the cache. I have asked customers to clear their browsers cache and cookies, but without any result.

I have disabled minimize HTML, I have the euro currency, and I have the correct Api key.

For the time being i have reinstalled version 3.0.2., as this version gives no problems.

### Environment
* PrestaShop version: 1.6.1.1 
* Mollie module version: 3.3.0

**Comment by snowycatsoftware** [comment] 2018-10-27 13:43
Hi @Huisdierdirect ,

We just tested this issue on a clean PS 1.6.1.1 environment using PHP 5.6.38 and Mollie module v.3.3.0. We can not reproduce this issue. All peyment methods are showing correctly and customers can place an order.

It seems something else // a different problem is causing this issue.

We checked your webshop and tried to place an order. However, it could not be placed. Using several valid addresses, a message is showing "there is no shipper / carrier available for this address".

We would advice you to check the blockpostcodenl module you're using.

We would also like to advice you to create a copy of your webshop and place it on a subdomain, so you have a test environment. This way you or your webdeveloper can check what is causing this issue.

Kind Regards

**Comment by Huisdierdirect** [comment] 2018-10-27 13:55
Hello,

It is correct that you could not place an order. You have selected a 
product that we do not send by external carrier. The product you 
selected is only being delivered by our own carrier.

If you use postal code 4354 AJ + housenumber 37, you will be able to 
place an order. Or just select a product like Barca Premium Adult with 
you own adress and you will also be able to place an order.

regards

Jan / Huisdier Direct



Op 27-10-2018 om 15:43 schreef Snowy Cat Software:

**Comment by snowycatsoftware** [comment] 2018-10-27 14:32
Hi @Huisdierdirect ,

We would like to ask you to contact us by e-mail (info[at]snowycatsoftware.com) after the test environment has been set up, and we will have a look at the issue.

Please provide us with the following:

- Employee account with SuperAdmin rights to the admin interface;
- FTP login.

Kind Regards

**Comment by firstred** [comment] 2018-10-27 16:17
@snowycatsoftware Have you tested a clean install or an upgrade from `3.0.2`?

**Comment by snowycatsoftware** [comment] 2018-10-27 16:31
@firstred ,

Yes, tested both ways. Works perfectly.

**Comment by firstred** [comment] 2018-10-27 16:36
Strange, aye!
I did notice some lag, however. For instance, switching from the Orders API to the Payments API w/ Klarna previously enabled, will still show Klarna on the checkout for some time, even though it is not supported:
![screenshot from 2018-10-27 18-36-23](https://user-images.githubusercontent.com/6775736/47606709-39957800-da17-11e8-9c82-2eede772c8bd.png)

**Comment by firstred** [comment] 2018-10-27 16:37
Could that be it?

**Comment by snowycatsoftware** [comment] 2018-10-27 17:29
You are right, just tested this, once with cache enabled and disabled. It makes no difference. Klarna keeps showing, even with the payments API enabled.

**Comment by firstred** [comment] 2018-10-29 06:19
I had a further look and noticed it only affects Klarna atm. It is limited to payment methods with `available = false` on the Payment API.

@Huisdierdirect Don't hesitate to reach out if you still can't upgrade to `v3.3.1`. Just drop @snowycatsoftware and email and we'll have a look. It would be a shame if you had to miss out on new features because of this issue!

**Comment by Huisdierdirect** [comment] 2018-10-31 20:13
Hello,

Was trying to install version 3.3.1 again today. At first install 
everything went fine. All payment methodes appeared.

After closing back-office and closing web-browser (automatically 
removing cache and cookies), and then restarting the back-office no 
payment methodes visible.

See attached screenshots.

After clicking on the button (try again) the payment methodes did 
appear. This is not correct; they must appear a soon as you open the 
module. This is the same problem my customers had last week.

So for the time being I am, again, going back to version 3.0.2, without 
Klarna.

Hope you can solve this.

Kind regards

Jan / Huisdier Direct


Op 29-10-2018 om 7:20 schreef Michael Dekker:

**Comment by dragonfly4** [comment] 2018-11-01 08:58
I had the same problem, PS 1.7.4.2 with Mollie 3.3.1
Payment icons and names not visible during checkout.
Cleared cache --> same issue
Re-organized the order under Mollie module options --> problem resolved

**Comment by firstred** [comment] 2018-11-01 09:05
Thanks @dragonfly4 for your feedback! That is very useful!

Now, I wonder why it is necessary to clear the cache and/or reorganize the payment methods after an update. That should not be necessary and I can imagine it is very confusing.

After the update can you remember whether you stayed on the Payments API or did it immediately show Orders API on the configuration page? I'm afraid, from the feedback we have received, that the module sometimes starts to reconfigure all the payment methods during an update.
Let's get to the bottom of this.

**Comment by snowycatsoftware** [comment] 2018-11-02 23:07
Hi @Huisdierdirect ,

A different merchant was coping with the same issue. We discovered this is a bug concerning the caching in some PrestaShop versions. We created a new bèta version, which should work in your case as well. Please follow the these steps:

- Install the Bèta version enclosed in this comment;
- Go to advanced parameters -> performance;
- Disable the cache, make sure the cache is set to "Recompile templates if the files have been updated" and save the settings;
- Make sure "Caching" on the bottom of the same page is turned off as well (and save the settings if needed).
- Clear the cache via the button on the top right of the same page;
- Clear cache manually as well via the FTP. Delete all the files and folders in the folders "/cache/smarty/cache" and "/cache/smarty/compile" EXCEPT FOR the index.php file.
- Delete the file named "class_index.php" in the "/cache" folder. PrestaShop will generate a new file.

Kind Regards

[mollie-v3.3.2-beta.4.zip](https://github.com/mollie/PrestaShop/files/2544358/mollie-v3.3.2-beta.4.zip)

**Comment by firstred** [comment] 2018-11-22 18:34
Closing due to no more response. Feel free to open a new issue if you still have problems.

**Closed by firstred** 2018-11-22 18:34 UTC

**Comment by Huisdierdirect** [comment] 2018-11-23 08:30
Good morning,

I replied the following on the 2nd to Snowy Cat software :

/quote//
/

/Hi,/

//

/Followed the below mentioned sequence and this is what i got ://
/

//

/[PrestaShop] Fatal error in module file 
:/home/deb79160/domains/huisdierdirect.nl/public_html/16/modules/mollie/upgrade/Upgrade-3.1.5.php://
//Call to undefined method Tools::clearAllCache()/

//

/regards/

/Jan//
//
//unquote

*
*/Have had no response afterwards. For the time being I'll use v.3.02.

I'll wait for the next update anyway, because I want to add a surcharge  
for the use of Klarna.
At the moment there is no possibility to add a surcharge. I'm hoping it 
will be implemented in the next update.

regards
Jan / Huisdier Direct

**/**/


Op 22-11-2018 om 19:35 schreef Michael Dekker:
