### ISSUE TITLE
Phone number issue

### ISSUE THREAD

**Issue by BricksDirect** [mollie/PrestaShop#227] opened 2020-10-26 18:37 UTC
### Expected behavior
It must be possible to insert phonenumber as the customer wants. In Mollie version 4.07 this is no problem.

### Actual behavior
When phonenumber is not in E.164 format. Customer sees following error:

Error executing API call (422: Unprocessable Entity): The 'phone' field should contain a valid phone number, in E.164 format. Field: billingAddress.phone. Documentation: https://docs.mollie.com/guides/handling-errors. Cart Dump: { "amount": { "currency": "EUR", "value": "12.98" },

### Steps to reproduce the behavior
Fill in phone number, not in E. 164 format.

### Environment
* PrestaShop version: 1.7.6.8
* Mollie module version: 4.08 and 4.09
* PHP version: 7.2.34

**Comment by SimonasB88** [comment] 2020-10-27 09:19
Hey @BricksDirect thanks, this issue is known and on our way on fixing.
We have backloged your request about this, we will update you about the fix.

Best Regards.

**Comment by Goedkoopsteverf** [comment] 2020-11-01 14:02
Advice don't install won"t work even what the develloper said, seach for a other PSP with betere payment plugins for Prestashop

**Comment by Maz-Invertus** [comment] 2020-11-03 09:04
Hi @Goedkoopsteverf . We do understand your frustration around the errors occurred. Our team tried to help you with the issues, but looks like there is a complex issue on your shop. Our team is here to help you. Unfortunately we couldn't reproduce the issue on a standard PrestaShop environment. As we see you have a customised configuration on your shop, could you share the below credentials to our support team email: support@invertus.eu that we could help you to solve your outstanding issue?

URL back office:
login back office:
password back office:
FTP host:
FTP login:
FTP password:
FTP port:

Looking forward to hearing from you

**Comment by SimonasB88** [comment] 2020-11-17 08:57
Hey @BricksDirect 
We have included this fix in 4.1.0 release, maybe we can close this issue and in case you will raise the new issue regarding 4.1.0?

Best Regards.

**Comment by SimonasB88** [comment] 2020-12-01 09:05
The issue was closed, due to the inactivity for some time.
If other issues will occur, please raise a new ticket.

Best Regards.

**Closed by SimonasB88** 2020-12-01 09:05 UTC
