### ISSUE TITLE
Cart cannot be loaded or an order has already been placed using this cart

### ISSUE THREAD

**Issue by MaartenPol** [mollie/PrestaShop#280] opened 2021-01-21 09:13 UTC
### Expected behavior
When starting the payment go to the Mollie page to pay the order.

### Actual behavior
Customers (not all) get an error when they want to pay.' An error occurred while initializing your payment. Please contact our customer support.' In the backend I see message: 

Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart --

Payments are configured with Orders API. Happens with different payment methods.

### Steps to reproduce the behavior
Put products in cart, go to checkout en start a payment.

### Environment
* PrestaShop version: 1.7.7.1 
* Mollie module version: 4.2.0
* PHP version: 7.3.26

**Comment by Saimis777** [comment] 2021-01-21 09:33
Hello, and thank you for your message.

Could you clarify which exact payment method is used when this error appears? And does the method have any restrictions in the back office? Navigate to your back office -> Payment -> Preferences -> Country restrictions, in there check if Mollie isn’t restricted to any country from the given list. As it could be that those payment methods you are using could be restricted.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by MaartenPol** [comment] 2021-01-21 09:55
We have customers saying it's happening to iDeal, Paypal and Creditcard. Not a single country restriction is set. (Not in Country Restirictions / Not is Mollie) All are enabled. 

We just had some contact with customers with similar product. One had restrictions in carriers. Could that be a problem?

**Comment by Saimis777** [comment] 2021-01-21 10:10
Thank you,

You can try to disable the carrier restriction, and see if the issue persists, but I highly doubt that would be the case. Would you be able to send us your front office / back office / FTP credentials, and full steps on how to reproduce the issue to - support@invertus.eu for further investigation?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by MaartenPol** [comment] 2021-01-21 10:26
I did that, same issue. 

I could reproduce the problem myself. I placed the same products in a cart and same carrier. I enabled all logs (to front too) and got this error:

`Cart Dump: [2021-01-21T11:24:06+0100] Error executing API call (422: Unprocessable Entity): The amount of the order does not match the total amount from the order lines. Expected order amount to be €21.06 but got €21.04. Field: amount. Documentation: https://docs.mollie.com/guides/handling-errors json: { "amount": { "currency": "EUR", "value": "21.04" }, "billingAddress": { "organizationName": "", "streetAndNumber": "Boeg 113", "city": "Groningen", "postalCode": "9733 ER", "country": "NL", "givenName": "Maarten", "familyName": "Pol", "email": "info@maartenpol.com", "phone": "+649105674" }, "shippingAddress": { "organizationName": "", "streetAndNumber": "Boeg 113", "city": "Groningen", "postalCode": "9733 ER", "country": "NL", "givenName": "Maarten", "familyName": "Pol", "email": "info@maartenpol.com", "phone": "+649105674" }, "redirectUrl": "https:\/\/www.levenvanhetland.nl\/module\/mollie\/return?cart_id=27122&utm_nooverride=1&rand=1611224646&key=fde230658a9bd7956dec4169068c1b25&customerId=3", "webhookUrl": "https:\/\/www.levenvanhetland.nl\/module\/mollie\/webhook", "method": "paypal", "metadata": { "cart_id": 27122, "order_reference": "FTKDFBJUX", "secure_key": "9df4b6ab304e5a063c32620196294726" }, "locale": "nl_NL", "orderNumber": "FTKDFBJUX", "lines": [ { "sku": "117\u00a40\u00a40", "name": "aubergine Black beauty", "productUrl": null, "imageUrl": null, "metadata": null, "quantity": 2, "vatRate": "9.00", "category": "", "unitPrice": { "currency": "EUR", "value": "1.95" }, "totalAmount": { "currency": "EUR", "value": "3.90" }, "discountAmount": [], "vatAmount": { "currency": "EUR", "value": "0.32" } }, { "sku": "1140\u00a40\u00a40", "name": "Black Cherry", "productUrl": null, "imageUrl": null, "metadata": null, "quantity": 1, "vatRate": "9.00", "category": "", "unitPrice": { "currency": "EUR", "value": "2.25" }, "totalAmount": { "currency": "EUR", "value": "2.25" }, "discountAmount": [], "vatAmount": { "currency": "EUR", "value": "0.19" } }, { "sku": "761\u00a40\u00a40", "name": "Druzba", "productUrl": null, "imageUrl": null, "metadata": null, "quantity": 1, "vatRate": "9.00", "category": "", "unitPrice": { "currency": "EUR", "value": "2.25" }, "totalAmount": { "currency": "EUR", "value": "2.25" }, "discountAmount": [], "vatAmount": { "currency": "EUR", "value": "0.19" } }, { "sku": "783\u00a40\u00a40", "name": "Slangenlook", "productUrl": null, "imageUrl": null, "metadata": null, "quantity": 1, "vatRate": "9.00", "category": "", "unitPrice": { "currency": "EUR", "value": "1.95" }, "totalAmount": { "currency": "EUR", "value": "1.95" }, "discountAmount": [], "vatAmount": { "currency": "EUR", "value": "0.16" } }, { "sku": "1126\u00a40\u00a40", "name": "Rosa bianca", "productUrl": null, "imageUrl": null, "metadata": null, "quantity": 1, "vatRate": "9.00", "category": "", "unitPrice": { "currency": "EUR", "value": "1.95" }, "totalAmount": { "currency": "EUR", "value": "1.95" }, "discountAmount": [], "vatAmount": { "currency": "EUR", "value": "0.16" } }, { "sku": "1193\u00a40\u00a40", "name": "Daslook", "productUrl": null, "imageUrl": null, "metadata": null, "quantity": 1, "vatRate": "9.00", "category": "", "unitPrice": { "currency": "EUR", "value": "2.50" }, "totalAmount": { "currency": "EUR", "value": "2.50" }, "discountAmount": [], "vatAmount": { "currency": "EUR", "value": "0.21" } }, { "sku": "285\u00a40\u00a40", "name": "Brandywine Sudduth", "productUrl": null, "imageUrl": null, "metadata": null, "quantity": 1, "vatRate": "9.00", "category": "", "unitPrice": { "currency": "EUR", "value": "2.26" }, "totalAmount": { "currency": "EUR", "value": "2.26" }, "discountAmount": [], "vatAmount": { "currency": "EUR", "value": "0.19" } }, { "sku": "", "name": "Shipping", "productUrl": null, "imageUrl": null, "metadata": null, "quantity": 1, "vatRate": "20.85", "category": null, "unitPrice": { "currency": "EUR", "value": "4.00" }, "totalAmount": { "currency": "EUR", "value": "4.00" }, "discountAmount": [], "vatAmount": { "currency": "EUR", "value": "0.69" } } ], "payment": { "webhookUrl": "https:\/\/www.levenvanhetland.nl\/module\/mollie\/webhook" } }

`

**Comment by Saimis777** [comment] 2021-01-22 17:06
@MaartenPol Thank you for that,

We are checking the issue further, I will keep you posted.

Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-01-27 16:04
Hello, the new version of Mollie - 4.2.1 was just released,

Please find the link for the download here - https://github.com/mollie/Prestashop/releases

And let us know with any feedback regarding the new version!

--
Best regards,
Invertus Support team

**Comment by MaartenPol** [comment] 2021-01-27 18:51
Just updated the version. I still receive the same error.

**Comment by petrovv77** [comment] 2021-01-29 17:28
Tested version 4.2.1 this morning. And it did go wrong. Double payment on order detail page and no invoice. I uninstalled mollie via prestahop, deleted the folder on the server and deleted all mollie database tables. I also deleted the last bad row in ps_order_payment database. It seems to be going well now, but it was a bit of a swear this morning.

**Comment by Saimis777** [comment] 2021-02-01 08:16
Thank you for your feedback!

We're currently checking this further, will update you later regarding this matter.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-08 17:03
Hello,

Just wanted to inform that the issue is still being investigated, and I will definitely update everyone once I will receive any news regarding this case.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-12 13:17
Hello,

Regarding this case, we're still clarifying it with the Mollie team, as soon as i'll receive any news, will inform you!

--
Best regards,
Invertus Support team

**Comment by MaartenPol** [comment] 2021-02-17 15:38
We found out that some products where where priced (for example) 2,245629 including taxes in the backend. In the front they are shown as 2.25. Combine some of those and then you got some cents difference. Could this be the issue?

**Comment by Saimis777** [comment] 2021-02-18 07:25
Hey @MaartenPol,

Thank you for that, I will clarify this with Mollie team, and get back to you as soon as possible!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-24 11:42
Hello,

Just a friendly reminder, that we are waiting on Mollie's approval how to proceed with this task, and which solution will be approved.

I will notify you once I'll have further information!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-03-01 12:41
Hello,

We already have a solution to this, and working on it, I will update you regarding the process, and when I will know when it will be released!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-03-08 12:37
Hello,

At the moment we are testing the implemented fix for the issue, and included it in the 4.2.3 release which is coming out really soon, I will notify you once it's released!

--
Best regards,
Invertus Support team

**Comment by MaartenPol** [comment] 2021-03-09 13:40
Hello!
thank you for the update. Just installed it. I will inform on any news regarding this issue.
Regards

**Comment by petrovv77** [comment] 2021-03-11 17:27
Hello,

Mollie 4.2.3 version:
Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart

This still occurs in the logbook on 1 of the 5 orders. I think it comes when a customer navigates right back after the order confirmation. And it is not a thing to fix. it's just the way it goes? For me it is not a problem. Everything is working properly for now.

**Comment by Saimis777** [comment] 2021-03-12 11:38
Hello @petrovv77 ,

We tried to reproduce the issue in a test environment. But couldn’t reproduce to get the error in logs from the front controller. Tried going back to order after payment confirmation. Tried to go back from the payment 3D window. Tried to reproduce with several payments credit card, paypal, iDeal.

Could you maybe specify the issue a bit further or give more details or steps of reproduction so we could identify the issue?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by petrovv77** [comment] 2021-03-12 16:09
@Saimis777 
Many orders further, no more relevant notification in logs. I'll report it again if it occurs.

**Comment by Saimis777** [comment] 2021-03-12 16:30
@petrovv77 ,

Excellent, thank you for the clarification.

--
Best regards,
Invertus Support team

**Comment by petrovv77** [comment] 2021-03-14 05:36
@Saimis777 
It happened again. All I can find on my side:

Apache access log:
`[13/Mar/2021:22:57:02 +0100] "GET /order-confirmation?id_cart=1469&id_module=134&id_order=338&key=*** HTTP/1.1" 200` 
**This is also the last row created for this user. The user has not requested any data from the server after the order confirmation page.**

It looks like the shopping cart has not been emptied. But when I look in Hotjar: The shopping **cart is empty for the customer** at the order confirmation page. 

**Prestashop admin Logs:**
 ![presta logs](https://user-images.githubusercontent.com/77987971/111057690-ba8b2800-8489-11eb-961a-8e99084a2b4f.png)
**Prestashop admin Carts:**
you can see that id 1470 is being created, while 1469 has just been completed. The fact that the amount of (1470 - €67,05) is different has to do with the fact that an item is not in stock after the order.
![presta AdminCarts](https://user-images.githubusercontent.com/77987971/111057685-b3fcb080-8489-11eb-96ff-203e472db5b6.png)

**Comment by Saimis777** [comment] 2021-03-15 12:45
Hello @petrovv77 ,

Could you also clarify if it's possible to receive the BO/FTP details for this shop to investigate it further? If yes, could you send them to support@invertus.eu?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-03-18 11:32
@petrovv77 ,

As we've investigated further, it seems to be a Prestashop issue which is not solved for a long time, you can read about it more here - https://github.com/PrestaShop/PrestaShop/issues/9866#issuecomment-616417249 

As I see there is still no relevant solution to this day for this issue to be solved.

I will close this issue for now, let me know if you will have any further questions or need help!

--
Best regards,
Invertus Support team

**Closed by Saimis777** 2021-03-18 11:32 UTC
Labels: Priority: Medium, Status:  In Progress, Type: Fix
