### ISSUE TITLE
momentarily in back-order (paid) status the e-mail is not send.

### ISSUE THREAD

**Issue by Frankyet** [mollie/PrestaShop#187] opened 2020-07-08 21:55 UTC
### Expected behavior
When an order is placed and paid the conformation e-mail is send and also payment is done e-mail, but if the order contain back-order articles the status is changed to momentarily in back-order (paid) but the e-mail from that status is not send.

### Actual behavior
When an order is placed and paid the conformation e-mail is send and also payment is done e-mail, but if the order contain back-order articles the status is changed to momentarily in back-order (paid) the e-mail from that status should send to customer

### Steps to reproduce the behavior
Make an order, with articles that are not in stock

### Environment
* PrestaShop version: 1.7.6.7.
* Mollie module version: 4.06
* PHP version: 7.3
![image](https://user-images.githubusercontent.com/22242384/86974301-600d2f80-c176-11ea-85f4-abb825059e7f.png)

**Comment by SimonasB88** [comment] 2020-07-09 06:31
Hey @Frankyet ,
Thank you for your insights, I will drop this to the team and update this thread when I will get the latest updates!

Best Regards.

**Comment by SimonasB88** [comment] 2020-07-10 13:47
Hey @Frankyet ,

Talked with the team, developers told that this feature is in the TODO, and will be updated in the upcoming 4.0.7. Probably it will be released next week.

Let's stay in touch, have a good day!

Best Regards.

**Comment by Maz-Invertus** [comment] 2020-08-07 15:08
Hi @Frankyet please have a look at [Mollie 4.0.7 release](https://github.com/mollie/PrestaShop/releases/tag/4.0.7) where you can find these new features:
-Added new order status “Completed” which is set when Mollie order is finished.
-Added option for PS1.7 to choose when to send order_conf email to the customer.
-Added new Mollie_payment email template that has Mollie payment link.
-Added “Second chance email button” in admin order list. Orders with Mollie payment will have option which allows merchant to send Mollie_payment email to the customer where he can finish his order payment.
-Added option to create order with Mollie payment from back office and send Mollie_payment mail to customer where he can finish his order.

**Comment by Frankyet** [comment] 2020-08-08 08:42
Hello,
I made a few test after removing first the old version and also the folders, installed the 4.07 version.
configured the module and made a few test orders.
found that in de back-office the Myparcel knob will not work anymore.
there will no e-mail send to customer when paid and no e-mail when paid and order is in back-order.
no conformation e-mail is send to customer when set when order is paid (only when set when order is created).


best  regards

![image](https://user-images.githubusercontent.com/22242384/89706145-49b7e680-d963-11ea-96a0-691a53a9644f.png)
![image](https://user-images.githubusercontent.com/22242384/89706160-62280100-d963-11ea-847d-2e9f90a2858b.png)
![image](https://user-images.githubusercontent.com/22242384/89706170-70761d00-d963-11ea-99e5-161eeb3685aa.png)

**Comment by SimonasB88** [comment] 2020-08-10 11:17
Hey @Frankyet  thanks for your insights!

Done some testing with the emails on PS1767 PHP 7.2 Multistores on localhost. Strange, re-sending emails are working OK.
![image](https://user-images.githubusercontent.com/29095235/89776725-1ddb6300-db13-11ea-823d-876d6a3d721e.png)

And yes, we are looking into "When Order is Paid" case, could not see that "payment" template is being sent in those circumstances.

![image](https://user-images.githubusercontent.com/29095235/89777276-0b155e00-db14-11ea-8026-8308026abdcc.png)


Regarding MyParcel button, it could be possibly a conflict with the code dependencies from the "Second Chance Email" sending button near. We are looking into this.

Could we debug and do testings directly on your server webshop? (the credentials you provided earlier, I see that it is OK, we can connect).

Looking forward to hearing from you!

**Comment by Frankyet** [comment] 2020-08-11 07:42
Hello  Simonas,

Yes re-sending will working but it is not sending in the first place when the status is set during the order.

Yes you can do testing on the server, the login for you is still active.

best regards,
Frank

**Comment by SimonasB88** [comment] 2020-08-11 13:02
Hey @Frankyet yes, ok, we will try to debug/fix this as fast as we can and we will update you. Thank you for your environment, we appreciate this much.

Best Regards.

**Comment by SimonasB88** [comment] 2020-08-17 13:25
Hey @Frankyet coming up with the news straight from the team:

Investigated why the “MyParcel” module doesn’t work with the Mollie module it seems the problem is in the “MyParcel” selector in JS, which is trying to select the penultimate element in the orders table. This can be fixed by switching module positions in BO. 
Like this: 
![image](https://user-images.githubusercontent.com/29095235/90399424-95753900-e0a3-11ea-8218-c11ccafbe195.png)

Now we switched the module position in your shop, but after the re-installation of module it will be necessary to reposition module again.

Next, Investigated on localhost and our demo server and it seems that emails are being sent when payment order is being paid or becomes backorder paid.

Thirdly, Investigated issue with backorder Paid status and order confirmation emails, when “Send order confirmation email” is set “When Order is Paid” and it seems that order_conf email is not being sent when the status is changed to backorder (paid).

![image](https://user-images.githubusercontent.com/29095235/90400575-5b0c9b80-e0a5-11ea-8460-40ddfb5644f3.png)

So, fixed this issue now when the setting “Send order confirmation email” is set “When Order is Paid”. it should send email conf when the status is changed to “Backorder (Paid)”. Of course, this fix will be added into upcoming releases as well.

Please check the updates, and let us know the feedback!
Best Regards.

**Comment by Frankyet** [comment] 2020-08-17 19:31
Hello Simonas, I have done this but now the resend button is not working annymore.

best regards

**Comment by SimonasB88** [comment] 2020-08-18 12:51
Hey @Frankyet thanks for notifying, we are re-checking this case on your environment, and we will let you know.

Best Regards.

**Comment by SimonasB88** [comment] 2020-08-19 11:36
Hello @Frankyet we have some news from the dev team, I guess it will be useful also for all community as well.

Regarding the button bug in Prestashop Order List, the problem is in the correct hook positioning with other module. Users should reposition the hook `actionAdminOrdersListingFieldsModifier` in Prestashop Design Positions once they have fresh-installed Mollie.
![image](https://user-images.githubusercontent.com/29095235/90629418-0a717b80-e228-11ea-8382-36e42f08631d.png)

Regarding the email sending, it is more of the @Frankyet server environment issue.
After debugging in clients demo shop, we saw that when Prestashop Core function is trying to send an email and it adds empty string. The reason is when Prestashop is trying to convert email to Punycode that uses INTL extension methods, that aren't installed in your server. The solution: ask server admin to install an INTL extension to your server and it should solve the problem.

So far those are the solutions, hope it will clear the path!

Best Regards.

**Comment by Frankyet** [comment] 2020-08-20 07:59
Hello Simonas,

The resend link Mollie button in Order list will not working for me, I think it is because I am using the Quick Order Preview Module from Myprestshop.eu, I have asked the dev Milos if he can fix this, he done it also for the Myparcel module button.

Regarding the email sending I have switched on in the admin panel the intl extension and it is working now, thanks for debugging Simonas and your dev team, good job.
![image](https://user-images.githubusercontent.com/22242384/90732531-8670cf80-e2cb-11ea-851c-4827f65ee666.png)


best regards

**Comment by SimonasB88** [comment] 2020-08-20 08:07
Hey @Frankyet , great news! 
Thank you for your insights also, in case there are some other questions/issues, please, rise the thread!

Have a great day!
Best Regards.

**Closed** 2020-08-20 08:08 UTC
