### ISSUE TITLE
Is it possible to stop changing the Klarna states?

### ISSUE THREAD

**Issue by jacob-v-dam** [mollie/PrestaShop#296] opened 2021-02-19 20:01 UTC
### Expected behavior
When i change a Klarna order it should not set it's own state.

### Actual behavior
When we change the state to shipped the order get's the Klarna shipped state:
![image](https://user-images.githubusercontent.com/310526/108555237-86db3900-72f5-11eb-9534-6c187911d292.png)

### Steps to reproduce the behavior
Get an authorized Klarna payment. Wait a few minutes, change the order state to shipped. The state will change to Klarna shipped directly.

### Environment
* PrestaShop version: 1.7.7.1
* Mollie module version: 4.2.2
* PHP version: 7.4

**Comment by Saimis777** [comment] 2021-02-22 11:50
Hey @jacob-v-dam ,

Thank you for your message!

I will clarify this issue with the team and get back to you as soon as possible!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-24 16:19
Hello @jacob-v-dam ,

I've got a clarification that this logic at the moment will stay as it is as we had to add custom klarna statuses because of the klarna logic where invoice can be created when authorized or shipped.

I will keep you posted if this will be edited or changed in any way, but at the moment that is how it works.

Maybe you have any other questions in the meantime?

--
Best regards,
Invertus Support team

**Comment by AmandaMollie** [comment] 2021-03-08 11:25
@jacob-v-dam - As @Saimis777 mentioned we've created these statuses in order to be able to delay the sending of the invoice until the Klarna order has been shipped. 

As we look into designing a solution that does not create an additional status, could you let me know if you also have the need for the delayed invoice? To put it simply, would option 2 work for your purposes? 

Options:
1. custom "shipped" status =  delayed invoice trigger 
2. standard "shipped" status = no delayed invoice trigger

**Comment by Saimis777** [comment] 2021-03-12 09:34
Hello @jacob-v-dam ,

Could you clarify if Amanda's 2nd suggested option would work for you? Or maybe you have another suggestion?

Let us know!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-03-23 11:37
Hello @jacob-v-dam ,

Could you clarify if you've managed to check the suggested options and if they would work for you?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-03-25 07:44
Hello @jacob-v-dam ,

Due to inactivity I will close this issue for now.

Let me know once you'll check the options or will have any ideas in mind!

Have a nice day!

--
Best regards,
Invertus Support team

**Comment by Maz-Invertus** [comment] 2021-04-08 05:59
Our team is working on the solution to add additional option when to create an invoice:

_When to create the invoice?_ 

Dropdown values:
--
Default
Authorized
Shipped


Description:
--
When do you want the invoice for Klarna Payments?
Default: Invoice creation is based on order settings > statuses. Custom status is not created.
On Authorize: Create a full invoice when the order is authorized. Custom status is created "Klarna payment authorized".
On Shipment: Create a full invoice when the order is shipped. Custom status is created "Klarna payment shipped".

**Comment by Saimis777** [comment] 2021-04-21 14:40
Hello,

A new version of Mollie was just released, with a solution included for you, you can download the latest version here - https://github.com/mollie/PrestaShop/releases/tag/4.2.4

We are closing this issue for now, if the issue is still there be sure to let us know, we'll reopen the issue!

And be sure to provide us feedback regarding the latest release!

--
Best regards,
Invertus Support team

**Closed by Saimis777** 2021-04-21 14:40 UTC
Labels: Priority: Medium, Release: Upcoming release, Type: Feature
