### ISSUE TITLE
Error in Mollie Dashboard / No order in backoffice PS

### ISSUE THREAD

**Issue by Sylvia78** [mollie/PrestaShop#118] opened 2019-08-02 12:22 UTC
### Expected behavior
After a payment there should be an order in the backoffice of Prestashop 

### Actual behavior
There is no order in the backoffice of Prestashop and on the Mollie dashboard I found this error: 
Aanroepen webhook mislukt met statuscode 500 (Got HTTP/1.1 500 Internal Server Error instead of 20x)

### Environment
* PrestaShop version: 1.7.5.1
* Mollie module version: 3.3.4
* PHP version: 7.1.30

**Comment by ArturasInvertus** [comment] 2019-08-05 07:21
Hi @Sylvia78 ,

Thanks for contacting us.

Issue appeared after you upgraded PrestaShop or Mollie module? Or you installed it fresh?
Also is your shop live or you testing in local environment? In case in local environment you can see some detailed info [here](https://help.mollie.com/hc/en-us/articles/213470409-My-webhook-URL-is-invalid-or-not-working-What-is-the-problem-).

Best

**Comment by Sylvia78** [comment] 2019-08-05 07:24
I updated the Mollie Module.
My shop is live but now with old Mollie module

**Comment by Torrentus** [comment] 2019-08-06 08:25
Not sure if this is related or a seperate issue, but since updating to the new version, our orders don't get a valid status any more. In the order overview view, the orders have status 'payment accepted', but when opening the order and looking at the status history, the status is not there. As a result of this, the order is also not flagged as a valid order. (Green box around order total in order overview).

Some screenshots of this behaviour:
_Correct order, after manually setting status to another one and back and thus validated order on top, order created by Mollie module is the bottom one:_
![image](https://user-images.githubusercontent.com/3865006/62523516-3942cc80-b834-11e9-8d76-1bef01d7e937.png)

_Order detail page; no status is set for the order:_
![image](https://user-images.githubusercontent.com/3865006/62523554-537caa80-b834-11e9-8d38-cbda96d534a3.png)

I upgraded from 3.3.5 to 3.4.0 yesterday.

**Comment by ArturasInvertus** [comment] 2019-08-06 09:11
Hi @Torrentus ,

We found some issues in admin order page JS global values. It was fixed in 3.4.1 version.

Could you please try and let me know if issue persist?

**Comment by Torrentus** [comment] 2019-08-06 09:20
I updated to 3.4.1, but new orders unfortunately still have no status.

**Comment by Sylvia78** [comment] 2019-08-06 13:04
I updated to 3.4.1 now and have the same issue as Torrentus.

I have an order after the payment but without a valid status

**Comment by ArturasInvertus** [comment] 2019-08-07 15:11
hi guys,

We released 3.4.2 version, issues is fixed. Could you please try and let us know?

**Comment by Sylvia78** [comment] 2019-08-08 18:12
Now the order has a valid status (payment accepted), but the backorder status for orders with out of stock products is not added.

**Comment by ArturasInvertus** [comment] 2019-08-09 14:12
This is weird. By any chance do you have a test environment where we could check it?
With the latest version we can't reproduce issue.

**Comment by Torrentus** [comment] 2019-08-10 06:51
For us, seems to be working. Not 100% sure yet as we received only one order yesterday because the plugin was disabled after the update (?). We should have tested. ;-)

**Comment by margud** [comment] 2019-09-06 14:08
This error and order status bug has been fixed in new [3.4.3](https://github.com/mollie/PrestaShop/releases/tag/3.4.3) release.

**Closed** 2019-09-06 14:08 UTC

**Comment by hknobbe** [comment] 2020-06-08 20:12
I know this is an old one, however after updating to 4.0.* versions I noticed that I kind of have the same problem. 

From mollie backoffice payment details:
Every time someone does a payment the first webhook call fails with error 500, then mollie sends the payment notification to the email and after that the webhook succeeds. 

However last weekend I had one that kept failing! And therefore the order status wasn’t updated.

Didn’t had this problem with the 3.*.* versions. Already reinstalled the module, no luck. Any suggestions or people with the same experience?
