### ISSUE TITLE
Payment recognition in split orders via orders API.

### ISSUE THREAD

**Issue by Apury** [mollie/PrestaShop#98] opened 2019-01-29 22:28 UTC
Hey there! 

I'm running Mollie 3.3.6 on PS 1.7.4.4 

I found another bug concerning the behavior of customers adding products with different carrier restrictions into their cart. 

In my case: 

Product A: 0.00€ Shipping 7.99€ [Carrier A]
Product B: 6.99€ Shipping 6.99€ [Carrier B]

What Prestashop does in this case, is to combine them into a single order, increasing the shipping price to the combined value of both carriers. 

And while the mollie payment gateway shows the correct price on the mollie payment page and requests the correct payment in the SEPA payment E-Mail, in the Backend it results in this note under "Orders -> Order ""Payment"

Warning €13.98 paid instead of €21.97 
This warning also concerns order #000095

Order #000095 being the second part of the combined, yet split order. 

The curious part however is, that in the Mollie information, it shows 

PAYMENT INFO
Transaction info
Transaction ID: XXXX
Date: 2019-01-29 23:18:12
Amount: €21.97

And lists both products. Product B for 9.99 and "Shipping" for a combined value of 14.98€ 

This information is displayed on the mentioned order#000095 aswell.

**Comment by firstred** [comment] 2019-01-29 22:46
Great you reported this one, thanks!

It's indeed a problem that's been in PrestaShop for a while, without much consequences for the rest of the system, because the majority of integrations relies on the order to be validated as a whole, rather than be fully paid due to the aforementioned bug. I think it must be somewhere in `PaymentModule::validateOrder`, which we now have ported over to the Mollie module (`Mollie::validateMollieOrder`. This should give us the opportunity to (finally)fix it instead :)

Could it be somewhere around this line?
https://github.com/mollie/PrestaShop/blob/master/mollie.php#L1394

How many invoices do you have? I have seen cases before where it would ignore part of the payment, due to it already having an invoice.

**Comment by firstred** [comment] 2019-01-29 23:24
Strange, I am unable to reproduce this. 

How was the price of Product A set to 0? Was that done with a price rule?

**Comment by Apury** [comment] 2019-01-29 23:53
It was set to 0 via a "specific prices" -100% rule in Products -> Pricing. 

I have one invoice for each of the products, as long as I set, in this case, the 0.00€ product's order to payment accepted. The whole thing wouldn't be much of a problem to me. Sure, it's annoying that customers get two confirmation mails and what not but the really problematic part, also for returning merchandise, is that one of the two items is kept at "awaiting bank wire payment"

**Comment by firstred** [comment] 2019-02-18 16:37
I have been able to reproduce this with a problematic module:

The order amount before the payment was €97, but right after the payment, the special order line added by this module was removed from the actual cart itself, lowering the amount to €95, right before the call to `PaymentModule::validateOrder`.
This means that even though the right amount was paid at Mollie, the amount that is marked as paid becomes max.  €95.

![screenshot from 2019-02-18 17-35-36](https://user-images.githubusercontent.com/6775736/52964832-a6a49300-33a3-11e9-932a-2ffd55d44912.png)
![screenshot from 2019-02-18 17-35-15](https://user-images.githubusercontent.com/6775736/52964833-a73d2980-33a3-11e9-9881-8e729953e2d6.png)

One solution is to double check the paid amount after `PaymentModule::validateOrder` was executed and compare it with the actual amount paid at Mollie, but that probably doesn't solve the underlying problem caused by cart splitting or a module like this one.

Do you also see the total cart value as the paid X instead of Y amount? Or does it correspond to the actual order amount?

**Closed** 2019-10-02 12:25 UTC
