### ISSUE TITLE
PaymentModule::validateOrder - Order Status cannot be loaded	

### ISSUE THREAD

**Issue by lexzz** [mollie/PrestaShop#190] opened 2020-07-29 07:41 UTC
### Expected behavior
Redirecting to the paymentpage of Mollie to make a iDeal payment,

### Actual behavior
After submitting the order in the cart, prestashop gives a internal server error.
Error in the log: PaymentModule::validateOrder - Order Status cannot be loaded	

### Steps to reproduce the behavior
Put products in cart and try to post the order

### Environment
* PrestaShop version: 1.7.6.3
* Mollie module version: 4.0.6
* PHP version: 7.2.31

**Comment by SimonasB88** [comment] 2020-07-29 07:59
Hey @lexzz thanks for your message.

Could you please show some screenshots from the debug mode? Or basically, could you reproduce the actual video screen caprute of this issue?

We will discuss with the team.

Best Regards.

**Comment by lexzz** [comment] 2020-07-29 08:15
Thank you for your answer.
I made a screencapture: https://youtu.be/Nb7v66VA47U

Let me know if you need more information.
Thank you in advance.

**Comment by SimonasB88** [comment] 2020-07-29 08:28
@lexzz thanks for your message with the reproduction.

Well, we might guess, that you have been upgrading the module from v.3.5 to the v4.0.6?

We would like to advice you to make the old v.3.5 module uninstall completely, and also check the option to delete all the folder of Mollie from your server.

Then install the new v.4.0.6 from the fresh and configure all the required module settings.

Let us know the checkouting results.

Best Regards.

**Comment by lexzz** [comment] 2020-07-30 07:22
@SimonasB88 the problem is fixed after reinstalling the plugin as you described.
Thank you for your answer.

Is it necessary to reinstall the plugin on each update?

**Comment by SimonasB88** [comment] 2020-07-30 08:42
Hey @lexzz thank you for the message! Great to know!

Well, so far it is the best approach to reinstall all the module, when users are upgrading from 3.5.5 to the 4.0.6, because there are many refactored changes in code, and that's why update execution is tricky. We know that this is kinda miserable case, we are looking forward to this fix in future. 

Best Regards.

**Comment by SimonasB88** [comment] 2020-08-11 14:52
Hey @lexzz just friendly follow-up about this case. Is it solved for you, and we can close this thread?

Best Regards.

**Closed** 2020-08-18 14:40 UTC

**Comment by icuMedia** [comment] 2020-10-11 10:29
I have the same exact issue, there's no option to delete all folders. After clicking uninstall -> delete there's no mollie folder in the modules folder anymore.

**Comment by SimonasB88** [comment] 2020-10-12 09:11
Hey @icuMedia what version of Prestashop are you using? is there a possibility for you to delete the folder manually via FTP then?

Best Regards.
