### ISSUE TITLE
BO error because of translations not escaped

### ISSUE THREAD

**Issue by Daaaaad** [mollie/PrestaShop#260] opened 2020-12-14 10:08 UTC
I just upgraded to v4.1.2 and I'm now getting a JS error IN the module configuration.

### Steps to reproduce the behavior

Install v4.1.2 on a fresh install of PrestaShop **in french**.

In the BO you will get a JS error in the console : 

`Uncaught SyntaxError: Unexpected identifier`

<img width="722" alt="Capture d’écran 2020-12-14 à 11 06 05" src="https://user-images.githubusercontent.com/167037/102068140-632eda80-3dfc-11eb-870d-fcd0a6b8e260.png">

Quotes are not escaped correctly...

### Environment
* PrestaShop version: 1.6.1.24
* Mollie module version: 4.1.2
* PHP version: 7.1.33

**Comment by Saimis777** [comment] 2020-12-14 13:25
Hello, thank you for your message.

We've registered your issue, and passed it to our team, we will look in to it, if any additional information will be needed, we will inform you, and get back to you with an answer ASAP!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2020-12-28 08:57
Hello, hope you're having a good day!

Sorry for the late reply, could you please check if the error persists now, if yes, would you be able to re-install, and check again?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2020-12-30 11:37
Hello,

As the issue was resolved, and due to inactivity, I will close the issue for now, if you will encounter any further errors, please let us know, we are here to help!

Best regards,
Invertus Support team

**Comment by Daaaaad** [comment] 2020-12-30 14:43
Hi @Saimis777,

Is there a new release somewhere? 🤔

What version should I test?

**Comment by Saimis777** [comment] 2020-12-30 15:07
Sorry for that, we've decided to include the fix in the upcoming update - 4.2.0, with all other fixes, and updates, it's going to be released really soon, and the update will be uploaded here - https://github.com/mollie/Prestashop/releases

Be sure to subscribe as a watcher on that repository, to get a notification once we release it!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-01-13 13:44
Hello @Daaaaad , hope you're having a nice day!

The official Mollie 4.2.0 was just released, the fix was implemented, you can download the latest version here - https://github.com/mollie/PrestaShop/releases/tag/4.2.0

Any feedback regarding the updated version is greatly appreciated!

--
Best regards,
Invertus Support team

**Comment by Daaaaad** [comment] 2021-02-08 11:15
Hello @Saimis777,

I just tested 4.2.0 release and the problem with "profile_id_message_empty" variable is fixed BUT the problem now occurs with "image_size_message" variable 😔

<img width="504" alt="Capture d’écran 2021-02-08 à 12 15 18" src="https://user-images.githubusercontent.com/167037/107212491-53e89980-6a07-11eb-965e-306decf1aa04.png">

**Comment by Saimis777** [comment] 2021-02-08 11:37
Hello @Daaaaad,

We really appreciate your feedback regarding the module, and sorry for the caused inconveniences, I will immediately assign a developer to investigate this issue!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-11 09:28
Hello @Daaaaad , hope you're having a nice day so far!

We've just launched the 4.2.2 Mollie version, maybe you could try and install it, and provide any feedback regarding the new version?

You can download the latest version here - https://github.com/mollie/Prestashop/releases

Also, this issue was fixed on PS 1.6 in French environment

![image](https://user-images.githubusercontent.com/75423142/107619671-3102f300-6c5c-11eb-8a36-9a2c99af5362.png)


Looking forward to your feedback!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-15 11:36
Helo,

Have you managed to install the latest version, and test if everything is okay?

Looking forward to your feedback!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-17 10:00
Hello @Daaaaad,

Just double checking if you've managed to check the latest version if the issue persists?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Daaaaad** [comment] 2021-02-17 14:00
Hi @Saimis777, I just checked quickly and everything seems to be ok. 

I'll let you know if I find some other bugs.

**Comment by Saimis777** [comment] 2021-02-17 16:10
@Daaaaad than you for your reply!

Glad that everything is working now, I will close this issue for now, and if you will find any further issues, or need help, please let me know!

--
Best regards,
Invertus Support

**Closed by Saimis777** 2021-02-17 16:10 UTC
