### ISSUE TITLE
missing or invalid field entity (phone number) is handled unprofessionally

### ISSUE THREAD

**Issue by pedalracer** [mollie/PrestaShop#231] opened 2020-10-29 15:27 UTC
### Expected behavior
If payment option is dependend on valid phone number it should make this clear when this one is entered.

Eg.
Klarna pay later seems to use this field entity for customer verification. At least the module api does.

### Actual behavior
If customer enters bogus telephone number on registration as most customers will do Klarna pay later option is available but fails to procede and to inform customer why it failed.

If merchant activates log error level this is rendered:
 Bei der Bearbeitung Ihres Auftrags ist ein Fehler aufgetreten:

    Error executing API call (422: Unprocessable Entity): The 'phone' field should contain a valid phone number, in E.164 format. Field: billingAddress.phone. 

### Environment
* PrestaShop version: 1.6.24
* Mollie module version: 4.0.9
* PHP version: 7.4.x

**Comment by SimonasB88** [comment] 2020-10-30 08:43
Duplicate of #227

Hey @pedalracer  thanks, this issue is known and on our way on fixing.
We have backloged your request about this, we will update you about the fix.

Best Regards.

**Closed** 2020-10-30 10:08 UTC

**Comment by SimonasB88** [comment] 2020-11-09 10:02
Apologies for the delay. It took some time to gather all the information from the team. Please find an explanation below. When user checkouts on the webshop, the phone number by default, should be inputed with + symbol. For example, if a user enters a number with the beginning +44 (valid UK) it is transferred the same to Mollie and Prestashop all OK.
When a user enters invalid code for example +000, and finishes checkouting, the Mollie API makes a validation of the phone number and doesn’t let it proceed with a payment.  So there is no problem at all from the technical side. Problem was only the error showing itself.
We made an update, that there would not be any useless error.
Hope explanation is clear for you.
Please let me know if you have any questions.
We will release the fix this week in the 4.1.0 release.

Best Regards.
