### ISSUE TITLE
Update from version 3 to 4, error 500 and missing payment methods

### ISSUE THREAD

**Issue by sdwebdesign** [mollie/PrestaShop#167] opened 2020-05-27 14:31 UTC
Upgrading from version 3 to 4, give the payment 500 error + the current payment methods are not available anymore after upgrade, you need to setup everything again.

Multistore. Version 1.7.6.1.

**Comment by basemedia** [comment] 2020-05-27 14:42
Same for us. I can't get the new module to work.

**Comment by Nathanpaternotte** [comment] 2020-05-28 08:13
Same for me, on Prestashop 1.7.6.1

**Comment by SimonasB88** [comment] 2020-05-28 08:27
Hello guys,
Sorry to hear about this, the issue is known and is handled at the development team.
We will update you when we will eliminate this issue.

Best Regards,
Invertus Support Team

**Comment by dtccomputers** [comment] 2020-05-28 13:01
Same here, from 3 to 4. On prestashop 1.7.6.5

**Comment by SimonasB88** [comment] 2020-05-28 13:56
Hello guys,
Please check the latest release regarding those mentioned bugs
https://github.com/mollie/Prestashop/releases

Have a great day,
Invertus Support Team

**Comment by Kevertje68** [comment] 2020-06-03 10:25
Hi

also with the new release, the problem with the error 500 page is not solved. In the backoffice of prestashop I see the following log: "PaymentModule::validateOrder - Order Status cannot be loaded" 

Hope it can be solved asap. There is no problem when using version 3 of this module

**Comment by SimonasB88** [comment] 2020-06-03 10:39
Hey @Kevertje68 sorry about this, assuring that the team got your message.
We are moving on to this issue.

Have a great day,
Invertus Support Team

**Comment by patrickderitter** [comment] 2020-06-03 15:55
I'm having the same issue.

**Comment by waschier-design** [comment] 2020-06-05 09:11
Problem are old / wrong methods in hook displaypaymentEU

+ Change: $apiMethod['id'] to $apiMethod['id_method']
+ Change: $apiMethod['name'] to $apiMethod['method_name']

Logo images: 
+Add:  $images = json_decode($method['images_json'],true);
+Change: $method['image']['size1x'] TO $images['size1x']
+Change $method['image']['size2x'] TO $images['size2x']

![image](https://user-images.githubusercontent.com/13886105/83858776-4616a200-a71d-11ea-8154-51a3db3ea61b.png)

**Comment by LMG-Jeffy** [comment] 2020-06-05 18:06
This problem happened to me too. Prestashop 1.7.6.5 and Mollie module 4.0.2.

I solved it by changing the config status in:
`/modules/mollie/controllers/front/payment.php:380`

The search was for a status "STATUS_MOLLIE_AWAITING" but Mollie only has the status
"MOLLIE_STATUS_OPEN" created in the config table of Prestashop.

Change:
`(int) Configuration :: get (Mollie \ Config \ Config :: STATUS_MOLLIE_AWAITING),`
To
`(int) Configuration :: get (Mollie \ Config \ Config :: MOLLIE_STATUS_OPEN),`

**Comment by margud** [comment] 2020-06-06 08:24
@LMG-Jeffy  you can find Config :: STATUS_MOLLIE_AWAITING in Configuration table with name mollie_awaiting.
It should exist in your table, if not there something is wrong and you should try to reset your module. Thanks to your comment we were able to found the different issues and fix it in the upcoming 4.0.4 release.
If you use Config :: MOLLIE_STATUS_OPEN it should have status 0 in your database.

**Comment by Kevertje68** [comment] 2020-06-08 06:28
I updated to 4.04 and now the issue is that during the checkout procdure, when I click on "Go to Payment" (on the page where you can select the carrier during the check out procedure), it directly goes to an error 500 page en there is no error log data in the back office of Prestashop.

The URL looks like this _shopname.nl/_index.php?controller=order

Hope it can be solved.

**Comment by SimonasB88** [comment] 2020-06-10 07:53
Hello @LMG-Jeffy have you managed to upgrade the module to v4.0.4? https://github.com/mollie/PrestaShop/releases/download/4.0.4/mollie.zip

Please let us know the outcome, if you are still experiencing the status problems.

Best Regards.

**Comment by Maz-Invertus** [comment] 2020-06-11 11:04
Hello @Toyboy125 and @Kevertje68 ,

Thank you for raising this issue. Our development team will act to this matter and investigate your issue. We are expecting to share the update with you tomorrow.

Thank you for using Mollie

**Comment by julianflapper** [comment] 2020-06-11 15:59
I am experiencing the same issue. Really in need of a fix!

**Comment by Maz-Invertus** [comment] 2020-06-12 08:32
Hi everyone,

Please try to reset the module. It should help.
We will also upload the latest release today.

**Comment by loetje88** [comment] 2020-06-12 16:49
Same here on prestashop 1.6.8.
Module is not usable at all. 

Good thing to start the weekend with. Thank you mollie.

**Comment by Toyboy125** [comment] 2020-06-15 08:11
Stange
locally it works now (xampp)
Version 4.0.5
but live site same fault.

_log status_ 
	PaymentModule::validateOrder - Order Status cannot be loaded	Cart	206

**Comment by Maz-Invertus** [comment] 2020-06-15 13:57
Hi Everyone,

We really appreciate your input in this community. We have added this issue to our backlog and planned the resources accordingly. In the meantime if you have similar issue, please try to reset the module or upgrade it to v 4.0.5. 
We are expecting to make the next release with this fix next week.

**Comment by Toyboy125** [comment] 2020-06-27 13:47
Version 4.0.6
Now testing on live site.
it seems good.
Thanks for the support.

**Comment by margud** [comment] 2020-06-28 13:10
Issue was resolved in [4.0.6](https://github.com/mollie/PrestaShop/releases/tag/4.0.6) release.

**Closed by margud** 2020-06-28 13:10 UTC
