### ISSUE TITLE
Module deactivated when opening Modules Tab

### ISSUE THREAD

**Issue by basemedia** [mollie/PrestaShop#123] opened 2019-08-09 10:13 UTC
### Expected behavior
Module has to stay active when opening "modules" Tab

### Actual behavior
Module disabled by Prestashop (see screenshot in Dutch)

"The following module (s) failed to update:
Mollie:
     No adjustment applied
     To prevent problems, this module is disabled"

### Steps to reproduce the behavior
Install module. Activate Mollie. Go back to Dashboard and then to Modules page.

### Environment
Prestashop 1.6.1.*
Mollie 3.4.2

![Screenshot 2019-08-09 at 12 11 56](https://user-images.githubusercontent.com/1645341/62772097-f3d60780-ba9e-11e9-92d5-a93289a008dc.png)

**Comment by ArturasInvertus** [comment] 2019-08-09 13:57
Hi @basemedia ,

Did you try to update module without disabling it first? Once PrestaShop disables module you can update it and it should work fine.

**Comment by basemedia** [comment] 2019-08-09 14:22
Working perfectly. Thanks.

**Comment by coMegaWebMaster** [comment] 2019-08-21 13:47
Hi,

Am having this same issue in PSv1.6.1.24 after trying to update to v3.4.2 from the previous version (tried from v3.4.0 and v3.4.1<what still shows like v3.4.0).
I tried to clear the cache, tried to install it again, tried to remove the module and install it fresh, but still getting that same error as above. The old module is active before the update, but then after the update that error comes and the module is inactive, trying to install it again and activation it again will result in the same error. 
A previous version is installed now and hopefully this issue can be resolved soon.
If any more information is needed then please let me know.

**Comment by ArturasInvertus** [comment] 2019-08-21 14:28
Hi @coMegaWebMaster ,

Seems were are still upgrade issues with 1.6 and we will investigate how to make it painless.

In meantime once you get message that "The following module (s) failed to update: Mollie:   To prevent problems, this module is disabled", just uninstall it and click install again.

**Comment by coMegaWebMaster** [comment] 2019-08-21 14:38
Hi @ArturasInvertus,

That did the trick, now it is working as it should, thx.

**Comment by coMegaWebMaster** [comment] 2019-09-06 14:30
Hi,

I had the same issue again when updating from v3.4.2 to version v3.4.3, so I did uninstalled it like last time and re-install it and set all the setting, but now the PayPal will not stay switched off, I tried a few things  and in the previous version it was working as it should.

**Comment by coMegaWebMaster** [comment] 2019-09-06 14:32
Also the sorting order of what payment first is not saved.

**Comment by coMegaWebMaster** [comment] 2019-09-06 14:56
I only installed v3.4.2 over v3.4.3 now and it is working as it should, degrading the module to a previous version does not give the error and the sorting and turn payment on/off is working, also it is showing the the frontoffice, it was also gone when updating to the new version,
Cache was cleared and payments where set in the Payments tab.

**Comment by coMegaWebMaster** [comment] 2019-09-18 13:29
This should also not been marked as closed as it is still not solved in the latest 3.4.3 version.

**Comment by margud** [comment] 2019-09-18 13:56
We couldn't reproduce the this issue with 3.4.3 version.
Maybe you could provide me your ftp login so we could check what we could do.

**Comment by coMegaWebMaster** [comment] 2019-09-18 14:05
To where can I send you this information, not here of course.

**Comment by margud** [comment] 2019-09-18 14:25
> To where can I send you this information, not here of course.

marius.gudauskis@invertus.eu

**Comment by coMegaWebMaster** [comment] 2019-09-26 08:08
Hi @margud,
Did you had a look at it?

**Comment by margud** [comment] 2019-09-26 13:55
We found out that in some older PS versions there are some issues with new country selector and module upgrade.
For now we managed to fix the issue with countries and module should work fine for you if you reinstall it clean.
I m still working on upgrade issue.
[mollie(7).zip](https://github.com/mollie/PrestaShop/files/3658098/mollie.7.zip)

**Closed** 2019-09-26 14:27 UTC

**Comment by coMegaWebMaster** [comment] 2019-09-26 16:05
Hi @margud,
I do not know if you want I open a new issue for this, otherwise you can move this message, but the sorting does still not work as I mentioned in https://github.com/mollie/PrestaShop/issues/123#issuecomment-528878527
I had to switch off PayPal now in Mollie it self that it does not show up in the module setting, as that the off switch is not working and also the sorting is not working, all the time it is reset and Apple Pay in on top.
