### ISSUE TITLE
Delay order confirmation in PrestaShop 1.6?

### ISSUE THREAD

**Issue by Daaaaad** [mollie/PrestaShop#300] opened 2021-03-01 14:49 UTC
When the module is installed on PrestaShop 1.7 we have the MOLLIE_SEND_ORDER_CONFIRMATION option : 

<img width="836" alt="Capture d’écran 2021-03-01 à 15 46 00" src="https://user-images.githubusercontent.com/167037/109513305-3e660d00-7aa5-11eb-8ef5-b84f47ced608.png">

Why don't you display this option on PrestaShop 1.6?

We also only want to confirm the ordre when the payment is processed 🤔

Can you help?

### Environment
* PrestaShop version: v1.6.1.24
* Mollie module version: v4.2.2

**Comment by Saimis777** [comment] 2021-03-02 10:59
Hello @Daaaaad ,

Thank you for your message, this is because there is no hook to disable sending on PS 1.6, therefore this option isn't available on 1.6 version.

What you can do on your PS is:

Disabled order_conf email for PS1.7. To disable it for PS1.6 you need to change PS core. classes/PaymentModule.php. you should comment out line 271:
 Mail::Send(intval($order->id_lang), 'order_conf', 'Order confirmation', $data, $customer->email, $customer->firstname.' '.$customer->lastname, NULL, NULL, $fileAttachment)

Let me know if you have any further questions or if we can close the issue!

--
Best regards,
Invertus Support team

**Comment by Daaaaad** [comment] 2021-03-02 11:08
Hello @Saimis777,

I don't want to disable the sending of the order_conf email but only send it when the user have actually paid.

Every other payment module I know - except other modules developed by Invertus - are only converting the cart to an order when the payment is successful... not before 😔

**Comment by Daaaaad** [comment] 2021-03-08 07:48
Hi @Saimis777, I really need a solution quickly.

I have multiple customers that are using your module and that's really a big issue 😔

**Comment by AmandaMollie** [comment] 2021-03-08 11:06
@Daaaaad 

The order creation payment is the intended behavior. 
This is because:
1. It's prestashop default and suggested process for order creation
2. It prevents overselling - if there is 1 product left and 2 people buy it at the same time, it may result in lack of inventory 
3. PrestaShop order reference is required to be sent to Mollie API 4. Capturing the order reference behavior payment allows merchants to capture missed conversions with second chance email functionality

**Comment by AmandaMollie** [comment] 2021-03-08 11:13
The order creation before payment is the intended behavior. This is because: 
1. It's prestashop default and suggested process for order creation
2. It prevents overselling - if there is 1 product left and 2 people buy it at the same time, it may result in lack of inventory 
3. PrestaShop order reference is required to be sent to Mollie API 4. 
4. Capturing the order reference behavior payment allows merchants to capture missed conversions with second chance email functionality

If you have additional questions, please feel free to contact me directly.

**Comment by Daaaaad** [comment] 2021-03-08 11:24
Hi @AmandaMollie,

I have no problem with the order creation (As long as you are able to recreate the cart if the payment fails).

The problem is the order confirmation email that is sent before the payment. Customers are getting an order confirmation even when they don't finalize the payment. That's a real problem.

Before there was an option in the module to only send the order confirmation email when paying:

<img width="783" alt="Capture d’écran 2021-03-08 à 12 22 28" src="https://user-images.githubusercontent.com/167037/110315052-fb59eb80-8008-11eb-9ef7-b306044f5533.png">

In the last version of the Mollie module this option was removed. We absolutely need it.

Regards,

David.

**Comment by AmandaMollie** [comment] 2021-03-08 11:34
@Daaaaad - you had this option in 1.6? If so, do you remember which Mollie plugin version you were using?

**Comment by Daaaaad** [comment] 2021-03-08 11:38
@AmandaMollie No, you're right.

So it's not possible to only send the order confirmation email when paying on PS 1.6.

But still possible on PS 1.7, correct?

**Comment by AmandaMollie** [comment] 2021-03-08 11:45
Correct, it is still possible on PS 1.7. 

The only alternative we can offer in PS 1.6 is the solution Invertus shared earlier in this chain to turn off the order confirmation email off. We recently had another dev in the community share his solution, but it has not be tested throughly yet. Maybe it is helpful for you for the short term. 

3 steps:

Pass the MOLLIE_SEND_NEW_ORDER configuration to 1 in the ps_configuration table (which corresponds to the option that is in the BO of the module when you are on a version 1.7 of PrestaShop)

In PaymentModule.php, deactivate the sending of the native mail only when Mollie is used:
- if (Validate::isEmail($this->context->customer->email)) {
+ if (Validate::isEmail($this->context->customer->email) && $order->module !== 'mollie') {

 When the webhook is called by Mollie, there is a fatal error. Indeed, the method used to translate the subject of the email is that of version 1.7. To correct it, you must modify the modules / mollie / src / Service / MailService.php file (however the correct method is used a few lines above in the sendSecondChanceMail function):

- $this->context->getTranslator()->trans(
-     'Order confirmation',
-     [],
-     'Emails.Subject',
-     $orderLanguage->locale
- ),
+ Mail::l('Order confirmation', (int)$order->id_lang),

**Comment by Daaaaad** [comment] 2021-03-08 12:32
Ok thx @AmandaMollie, I'll test this fix 👍

I have another question regarding the Mollie module, how could I contact you directly?

**Comment by Saimis777** [comment] 2021-03-12 09:54
@Daaaaad ,

If you have any further questions, or need clarifications, you can always open a new issue.

Have you managed to test the suggested fix? Maybe you have any further questions?

Let us know!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-03-18 08:22
Hello @Daaaaad ,

Due to inactivity I will close this issue for now, let me know if you will have any further questions, or will need any assistance!

Have a nice day,

--
Best regards,
Invertus Support team

**Closed by Saimis777** 2021-03-18 08:22 UTC
Labels: Priority: Medium, Status: On Hold, Type: Feature
