### ISSUE TITLE
Payment method not listed on invoice

### ISSUE THREAD

**Issue by Johnwulp** [mollie/PrestaShop#756] opened 2023-07-07 08:23 UTC
### Expected behavior
Payment method listed on invoice

### Actual behavior
Payment method not listed on invoice

<img width="506" alt="invoice cropped" src="https://github.com/mollie/PrestaShop/assets/879840/b81940ff-cc4d-47fc-8a91-d10281ae5983">

### Steps to reproduce the behavior
Customer buys something, invoice is sent and available in prestashop. 

### Environment
* PrestaShop version: 1.7.8.9
* Mollie module version: 6.0.0
* PHP version: 7.4.33

Maybe this issue is not related to this plugin, but before we updated to v6.0.0 this used to work without any issue.

<img width="445" alt="Old invoice cropped" src="https://github.com/mollie/PrestaShop/assets/879840/3211a447-9960-45f7-bd5a-ac56dd6f5206">

**Comment by justelis22** [comment] 2023-07-11 05:26
Hello there @Johnwulp,

We will check this issue and get back to you as soon as we have some updates.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2023-07-11 07:22
@Johnwulp,

We have analyzed the issue, and it works as expected from our side. That being said, could you please send us access to your shop (FTP and BO) credentials to our email support@invertus.eu so that we could dive deeper into this case?

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2023-07-19 13:59
Hello there @Johnwulp,
Thanks for waiting!

Our developer investigated the issue and it seems like there was an issue during the upgrade process of the module and the database table columns didn't update.
We are not 100% sure, but this could be related to your MySQL user's permissions being too low, as we have checked other tables that should have updated during the upgrade process and they did because they didn't use such sensitive actions.
This issue would come up with other upcoming Mollie versions (such as 6.0.1), as we do upgrade the database table structure.

**A possible fix for everyone facing this issue:**
Manually execute SQL command inside the database manager software:
`ALTER TABLE ps_mollie_payments ADD `mandate_id`/ VARCHAR(64);`

Please let us know if that helped!

Best Regards,
Invertus Support team.

**Comment by Johnwulp** [comment] 2023-07-21 22:07
Hi, thanks for this update. I can’t test it right away but will send an update somewhere end August. JOp 19 jul. 2023 om 15:59 heeft justelis22 ***@***.***> het volgende geschreven:﻿
Hello there @Johnwulp,
Thanks for waiting!
Our developer investigated the issue and it seems like there was an issue during the upgrade process of the module and the database table columns didn't update.
We are not 100% sure, but this could be related to your MySQL user's permissions being too low, as we have checked other tables that should have updated during the upgrade process and they did because they didn't use such sensitive actions.
This issue would come up with other upcoming Mollie versions (such as 6.0.1), as we do upgrade the database table structure.
A possible fix for everyone facing this issue:
Manually execute SQL command inside the database manager software:
ALTER TABLE ps_mollie_payments ADD mandate_id/ VARCHAR(64);
Please let us know if that helped!
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2023-08-01 07:41
Hi there @Johnwulp,

I will close the issue, if you still manage to recreate the issue, please reply here, and we will reopen it.

Best Regards,
Invertus Support team.

**Comment by Johnwulp** [comment] 2023-08-15 13:55
Hi, i added the sugested column: `ALTER TABLE ps_mollie_payments ADD mandate_id VARCHAR(64);`
![image](https://github.com/mollie/PrestaShop/assets/879840/573deb36-235b-4c6c-90d7-4fda239e8535)

Waited for a new order, but the column is not filled with anything.
![image](https://github.com/mollie/PrestaShop/assets/879840/70ddde1c-11bc-465f-af69-eacb7afe1a8c)

Also the payment method is not visible on the invoice.
![image](https://github.com/mollie/PrestaShop/assets/879840/b4f7e6e3-0d73-460f-8d18-bdf32e9d48b4)

Anything else that could be wrong?

**Comment by justelis22** [comment] 2023-08-16 08:08
Hi @Johnwulp,

We will check it and get back to you as soon as possible.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment] 2023-08-29 11:05
Hi there @Johnwulp,
Thanks for waiting!

Could you please share your shop backup with us? We have been analyzing the issue, but it seems like the issue is related to your shop and not the Mollie module, at least from what we can see now.
We would need your shop files and the database, you can delete all of the sensitive data before sharing it with us.
Please send it to support@invertus.eu.

Waiting for your reply!

Best Regards,
Invertus Support team.

**Comment by Johnwulp** [comment] 2023-08-30 06:31
Hi @justelis22,

Can you please use all the database and files that i have send before? I only added the column with `ALTER TABLE ps_mollie_payments ADD mandate_id VARCHAR(64);`

**Comment by justelis22** [comment] 2023-08-31 08:37
Hi @Johnwulp,

I wrote you an email regarding the backup.

Waiting for your reply!

Best Regards,
Invertus Support team.

**Comment by Johnwulp** [comment] 2023-08-31 11:14
Hi @justelis22, 

I have send the link to the backup files again. 
Thanks!

**Comment by ausrinekr** [comment] 2023-09-05 12:09
Hi there @Johnwulp ,

Developer tested the sent shop. The version was 6.0.0 so upgraded it to 6.0.3 (latest one), mandate_id was added as well as this probably was an old dump. The developer found out that your module “customorderreference” and overrides in “override/PaymentModule.php” are the reason why issues persisted with new orders (before disabling these changes we could not reach confirmation page after order creation) and invoices where the payment method was not displayed.

I hope this was helpful.

Best Regards,
Invertus Support team.

**Comment by Johnwulp** [comment] 2023-09-08 10:01
Hi @ausrinekr, we are going to deactivate this module. Many thanks for help finiding the cause of this issue.

**Comment by mandan2** [comment] 2023-09-12 06:21
Hello, @Johnwulp 

Is everything fine at the moment? Did module deactivation helped to fix the issue?

Best regards,
Invertus Support team.

**Comment by Johnwulp** [comment] 2023-09-18 08:49
Hi, we tested it for a while, but still we have the same issue. Do we need to take some extra steps?

![image](https://github.com/mollie/PrestaShop/assets/879840/714b81a0-1383-469d-aa47-692386c4d94d)

**Comment by justelis22** [comment] 2023-09-19 09:01
Hello there @Johnwulp,

It’s still possible that your specific overrides are not removed from /override/*. It’s likely that other modules have inserted their overrides too so just deleting files could cause more harm. 

Our recommendation would be to get developer assistance to do this kind of job if you are not familiar with overrides, as at the moment, we do not provide custom development services.

Let me know if you have any other questions!

Best regards,
Invertus Support team.

**Comment by Johnwulp** [comment] 2023-09-25 11:35
Hi, we removed all the overrides. The custom order refference is not working anymore as expected since we have the regular (not desired) prestashop order generated id. 
![image](https://github.com/mollie/PrestaShop/assets/879840/94c2510f-70cb-40f9-8b00-4cd6fe4c313a)

Still we have the same issue. Is there anything else we could check?

**Comment by justelis22** [comment] 2023-09-27 06:17
Hi @Johnwulp,

We will talk internally and try to understand what else could be the issue and get back to you with an update.

Best regards,
Invertus Support team.

**Comment by justelis22** [comment] 2023-10-04 06:57
Hello @Johnwulp,
Thanks for waiting!

We have analyzed the issue and debugged your shop locally.
After removing the overrides our developers managed to fix the issue, and I was informed that this is related to your shop and not the Mollie module.

As this is an issue on your system, I would suggest reaching out to a developer, who could help you with the overrides.

If you have any questions, don't hesitate to reach out.

Best regards,
Invertus Support team.

**Comment by justelis22** [comment] 2023-10-16 07:47
Hi there,

As there were no updates for a few weeks, I am closing this issue.

If you have any other questions, do not hesitate to reopen the case.

Best regards,
Invertus Support team.

**Closed by justelis22** 2023-10-16 07:47 UTC
