### ISSUE TITLE
Error executing API call (422: Unprocessable Entity):

### ISSUE THREAD

**Issue by Maikel726** [mollie/PrestaShop#234] opened 2020-11-05 12:24 UTC
### Expected behavior
When you select Pay later as payment method it should bring you to the Pay later (klarna) payment screen.

### Actual behavior
In version 4.09 and 4.08 it crashes with the follow message: Error executing API call (422: Unprocessable Entity): The 'phone' field should contain a valid phone number, in E.164 format.

### Steps to reproduce the behavior
Select Pay later (Klarna) as payment method and fill in the information for it and start the payment.

### Environment
* PrestaShop version: 1.7.6.7
* Mollie module version: 4.0.9
* PHP version: 7.0.33

**Comment by SimonasB88** [comment] 2020-11-05 14:41
Duplicate of 234#

Hey @Maikel726  thanks, this issue is known and on our way on fixing.
We have backloged your request about this, we will update you about the fix.

Best Regards.

**Comment by SimonasB88** [comment] 2020-11-09 10:00
Apologies for the delay. It took some time to gather all the information from the team. Please find an explanation below. When user checkouts on the webshop, the phone number by default, should be inputed with + symbol. For example, if a user enters a number with the beginning +44 (valid UK) it is transferred the same to Mollie and Prestashop all OK.
When a user enters invalid code for example +000, and finishes checkouting, the Mollie API makes a validation of the phone number and doesn’t let it proceed with a payment.  So there is no problem at all from the technical side. Problem was only the error showing itself.
We made an update, that there would not be any useless error.
Hope explanation is clear for you.
Please let me know if you have any questions.
We will release the fix this week in the 4.1.0 release.

Best Regards.

**Comment by SimonasB88** [comment] 2020-11-17 08:56
Hey @Maikel726 
We have included this fix in 4.1.0 release, maybe we can close this issue and in case you will raise the new issue regarding 4.1.0?

Best Regards.

**Comment by Maikel726** [comment] 2020-11-17 09:08
Hey @SimonasB88 

When version 4.1.0 is released I will see if it is resolved, if not I will let you know and create a new issue.

**Comment by Maikel726** [comment] 2020-11-17 10:04
Hey,

Still getting a error when trying to use Pay later, 

Cart Dump: { "amount": { "currency": "EUR", "value": "126.90" }, "billingAddress": { "organizationName": " ", "streetAndNumber": "De Gruisdonk 5", "city": "Venlo", "postalCode": "5928 RT", "country": "NL",

**Comment by SimonasB88** [comment] 2020-11-17 10:21
@Maikel726 can you copy the whole error here?

**Comment by SimonasB88** [comment] 2020-11-17 10:22
@Maikel726 please reset the module after upgrade and try once again.

**Comment by Maikel726** [comment] 2020-11-17 10:26
Hey @SimonasB88 

I tried to reinstall the Mollie module ( included deleting the map ) still getting this error:

Cart Dump: { "amount": { "currency": "EUR", "value": "126.90" }, "billingAddress": { "organizationName": " ", "streetAndNumber": "De Gruisdonk 5A", "city": "Venlo", "postalCode": "5928 RT", "country": "NL", "givenName": "Maikel", "familyName": "Mollie", "email": "info@ivolved.nl", "phone": "+773968147" }, "shippingAddress": { "organizationName": " ", "streetAndNumber": "De Gruisdonk 5A", "city": "Venlo", "postalCode": "5928 RT", "country": "NL", "givenName": "Maikel", "familyName": "Mollie", "email": "info@ivolved.nl", "phone": "+773968147" }, "redirectUrl": "http:\/\/autoonderdelenexpres.nl\/module\/mollie\/return?cart_id=67&utm_nooverride=1&rand=1605608696&key=52b8f9970d31b68251e928f5523e8a00&customerId=25", "webhookUrl": "http:\/\/autoonderdelenexpres.nl\/module\/mollie\/webhook", "method": "klarnapaylater", "metadata": { "cart_id": 67, "order_reference": "1420", "secure_key": "7f957cc9d3c77d3712a959370fe2fb2a" }, "locale": "nl_NL", "orderNumber": "1420", "lines": [ { "sku": "4861\u00a40\u00a40", "name": "CAM (MAC) dakdragers aluminium Volkswagen Passat VII Alltrack 5-dr Estate 2012-2015 met open dakrailing", "productUrl": null, "imageUrl": null, "metadata": null, "quantity": 1, "vatRate": "21.00", "category": "", "unitPrice": { "currency": "EUR", "value": "119.95" }, "totalAmount": { "currency": "EUR", "value": "119.95" }, "discountAmount": [], "vatAmount": { "currency": "EUR", "value": "20.82" } }, { "sku": "", "name": "Shipping", "productUrl": null, "imageUrl": null, "metadata": null, "quantity": 1, "vatRate": "0.00", "category": null, "unitPrice": { "currency": "EUR", "value": "6.95" }, "totalAmount": { "currency": "EUR", "value": "6.95" }, "discountAmount": [], "vatAmount": { "currency": "EUR", "value": "0.00" } } ], "payment": { "webhookUrl": "http:\/\/autoonderdelenexpres.nl\/module\/mollie\/webhook" } }

**Comment by SimonasB88** [comment] 2020-11-17 11:29
Hey @Maikel726 this is really very strange... Phone number now it is not in the spotlight, regarding this error.

Are you using One page checkout? Or have you customized your order functionalities in your Prestashop somehow?

Best Regards.

**Comment by Maikel726** [comment] 2020-11-17 11:37
Hey @SimonasB88 

I am using a 3th party one page checkout, but before this issue the Mollie module worked fine.

**Comment by SimonasB88** [comment] 2020-11-17 11:44
@Maikel726 that could make sense about the error that you are receiving. I have to check this with the developers.

I guess we could try to investigate the issue internally.
In order to investigate your issue and help you efficiently, can you send us an access to your backoffice with its url and a FTP access to your store:

URL back office:
login back office:
password back office:

FTP host:
FTP login:
FTP password:
FTP port:

Send everything to support@invertus.eu

Thanks.
Best Regards.

**Comment by SimonasB88** [comment] 2020-11-20 07:18
Ticket closed, successfully fixed for the client, the fix will be included in the next Mollie Github release.

Best Regards.

**Closed by SimonasB88** 2020-11-20 07:18 UTC
