### ISSUE TITLE
Payment above 1000 in 4.0.9 > Wrong amount to Mollie!

### ISSUE THREAD

**Issue by remcotjeerdsma** [mollie/PrestaShop#241] opened 2020-11-13 09:47 UTC
### Expected behavior
Initiate payment with correct amount, don't log payments for different amounts then the actual payment.

### Actual behavior
Payment with wrong amount is initiated, completed and order is marked as paid although it is not (entirely)!

### Steps to reproduce the behavior
Since updating to 4.0.9, I experience that orders above 1000 euro are passed on to Mollie as the payable amount/1000. 
This probably has to do with following change in the changelog:
_Fixed issue with order amount bigger then 1000. Mollie wouldn’t accept amount if it was displayed like 1,000.00. Now we send amount like 1000.00._

Example:
Total order amount: € 3.058,99
Mollie payment is initiated for the amount of € 3,06, completed and order is then marked as paid. 
Also, a payment is inserted in the prestashop 'payments' section of the order for the full amount € 3.058,99.

Please input the actual paid amount in payments that you add to orders. That would have made this error more visible.
And also, of course, fix the error where the wrong amount is passed on to Mollie.

### Environment
* PrestaShop version: 1.7.6.7
* Mollie module version: 4.07
* PHP version: 7.2.34

**Comment by remcotjeerdsma** [comment] 2020-11-13 09:54
![ErrorScreenshot](https://i.imgur.com/tSQcqsL.png)

**Comment by SimonasB88** [comment] 2020-11-13 12:35
Duplicate of #236 

Hello @remcotjeerdsma thanks for your report, we agree it is annoying and confusing thing.
Have you tried the 4.0.9 here from github?

Best Regards.

**Comment by SimonasB88** [comment] 2020-12-01 09:03
Hello @remcotjeerdsma have you tried the 4.1.1 release and tried to reproduce this issue?

Best Regards.

**Comment by SimonasB88** [comment] 2020-12-08 08:15
Hello dear friends, the case is closed due to inactivity for some time.
Please kindly raise a new ticket in case there is an issue.

Best Regards
Invertus Support Team

**Closed by SimonasB88** 2020-12-08 08:15 UTC
