### ISSUE TITLE
With Klarna no mail alert new order

### ISSUE THREAD

**Issue by MaartenPol** [mollie/PrestaShop#316] opened 2021-04-07 12:33 UTC
### Expected behavior
Receive an email from PrestaShop Mail Alerts-module on shops email address when a new order is placed and payed with **Klarna**. 

### Actual behavior
No mail is send to the show shops email address when payment method is Klarna. Other payment methods work as designed.

### Environment
* PrestaShop version: 1.7.7.3 
* Mollie module version: 4.2.3 
* PHP version: 7.3.27

**Comment by Saimis777** [comment] 2021-04-07 14:56
Hello @MaartenPol ,

Thank you for your message!

We will check with the reported issue, and let you know!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-04-08 15:15
Hello @MaartenPol ,

Unfortunately we could not reproduce the issue, maybe you could send us your BO/FTP credentials to - support@invertus.eu so we could try to replicate it there? Also, be sure to send the credentials directly to the email address, do not reply to the email via Github, as Github might share the email as a comment under the issue.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-04-12 12:10
Hello @MaartenPol ,

Could you clarify if it will be possible to receive the credentials for the following issue investigation?

--
Best regards,
Invertus Support team

**Comment by MaartenPol** [comment] 2021-04-12 13:02
Hello@Saimis777 

on it's way!

**Comment by Saimis777** [comment] 2021-04-14 15:12
Thanks @MaartenPol ,

We've received them, and will get back to you ASAP!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-04-19 12:37
Hello @MaartenPol ,

Just wanted to inform you that we are still working on the case, I will keep you posted!

Thank you for your patience!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-06-04 13:45
Hey!

The 4.3.0 version was released, and your  fix is included!

I've included the pull request, you can download the new version here - https://github.com/mollie/PrestaShop/releases/tag/4.3.0

Any feedback provided is greatly appreciated!

--
Best regards,
Invertus Support team

**Closed by Saimis777** 2021-06-04 13:45 UTC
Labels: Priority: Medium, Release: Upcoming release, Type: Bug
