### ISSUE TITLE
Bank transfer status not updated when switched to other payment method

### ISSUE THREAD

**Issue by Torrentus** [mollie/PrestaShop#46] opened 2018-04-10 08:42 UTC
If a user pays with the bank-transfer method, since a few months, Mollie gives the customer the option to change his mind and switch to a different payment method, such as credit-card or iDeal, at a later point in time. 

If the customer completes the payment using one of these different methods, then the status in Prestashop remains 'Waiting for bank transfer' although payment is completed already (in Mollie dashboard).

**Comment by snowycatsoftware** [comment] 2018-04-10 09:01
Hi Remco,

Thank you for taking the time to report this issue. The same issue was reported a while ago and we fixed this in one of the latest updates. 

Which version of the Mollie module are you currently using? We just tested it with the latest version (v2.0.4) and everything seems te be working fine.

If you are currently using an older version of the Mollie module, please upgrade to the latest version. Please test it on your development environment first before placing it on the production site, and let us know if the issue is solved so we can close it. 

If you have any questions please let us know, we are happy to help out.

Kind regards

**Comment by snowycatsoftware** [comment] 2018-04-26 08:56
Hi @Torrentus ,

We are closing this issue. If you have any other questions, please let us know.

Kind regards

**Closed by snowycatsoftware** 2018-04-26 08:56 UTC
