### ISSUE TITLE
orders with paypal and bank transfer cancelled by Mollie

### ISSUE THREAD

**Issue by Ditwo** [mollie/PrestaShop#281] opened 2021-01-21 09:20 UTC
Hello Team,
Since yesterday and just after the message "Mollie should be upgraded" displayed on the BO modules page, orders with paypal or by bank transfer methods are cancelled by Mollie a little while later.
This was the case until the upgrade to version Mollie 4.2.0.
How can this be prevented in the future?
It's very annoying because Paypal orders are accepted then cancelled, credit notes have to be made, customers are not happy.

### Expected behavior
The status of Paypal and bank transfer orders should not be affected by Mollie.

### Actual behavior
The paypal order is passed, payment confirmed. Then the status becomes cancelled. In the left column on the Back office order page, the icon is "m", the icon of Mollie.
The bank transfer order is passed, awaiting payment. Then the status becomes cancelled. In the left column on the Back office order page, the icon is "m", the icon of Mollie.
![Capture](https://user-images.githubusercontent.com/10560114/105329035-febc2380-5bd0-11eb-8bc7-21ec6f726f50.JPG)

### Steps to reproduce the behavior
A message was displayed in back office on 20/01/21 5:30pm, saying that Mollie should be upgraded. From this time, all the orders with Paypal and bank transfer are cancelled by Mollie. Until this morning the upgrade to 4.20.

### Environment
* PrestaShop version: 1.7.6.5
* Mollie module version: 4.1.3
* PHP version: 7.2

Thanks for your return,
Regards, 
Denis

**Comment by Ditwo** [comment] 2021-01-21 09:30
Sorry, it is still happening, despite the upgrade to 4.2.0.
Please help :(

**Comment by Saimis777** [comment] 2021-01-21 09:30
Hello, and thank you for your message.

Just to clarify, only when the message to update Mollie version appeared this started happening? You didn't upgrade to 4.2.0 version, right? Were there any other changes made or updates? Or absolutely nothing was changed?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by Ditwo** [comment] 2021-01-21 09:53
Hello Team,

Yes. I've just noticed the message yesterday but I didn't have time to upgrade.
No changes or no updates, since this morning and the upgrade to 4.2.0.
Meanwhile the orders have been cancelled automatically.
Example :
The latest paypal order created at 9:19am today has been cancelled 10:12.
![Capture](https://user-images.githubusercontent.com/10560114/105333863-80fb1680-5bd6-11eb-9dfd-276dcd281742.JPG)

Since then, there have been no cancelled orders. I will keep you update.

Best regards,
Denis

**Comment by Saimis777** [comment] 2021-01-21 10:10
Thank you for the clarification, 

Would you be able to send us your front office / back office / FTP credentials, and full steps on how to reproduce the issue  to - support@invertus.eu for further investigation?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by Ditwo** [comment] 2021-01-21 10:48
ok, done.
Thanks and regards
Denis

**Comment by Saimis777** [comment] 2021-01-21 15:06
Hello @Ditwo ,

In this picture, it seems that Paypal itself canceled the order. Because mollie cant change the status of other payments statuses, because mollie module cancels the order by transaction or order id it depends which API you are using which is unique for every payment/order and it is created only then when payment/order is created with mollie module. So mollie couldn’t cancel the order in prestashop without having a transaction/order id. 


![image](https://user-images.githubusercontent.com/75423142/105369079-dea95600-5c0a-11eb-8d1d-17b2a39482d9.png)
 
From this picture i can tell that only order status picture is bugged. Because mollie doesn’t even have “CANCEL” status. This could happen after upgrading module version. but it seems that now the problem isn’t appearing now. 


![image](https://user-images.githubusercontent.com/75423142/105369130-eb2dae80-5c0a-11eb-8cb2-76dce0a56fa2.png)
 
And I think that provided account doesn’t have all permissions, because it seems that with the provided account we can’t check the mollie module configurations. 
And here’s a link to check when mollie cancels payments on specific payment method
https://docs.mollie.com/payments/status-changes

Let us know if it's possible to grant further permissions to the given account!

Best regards,
Invertus Support team

**Comment by Ditwo** [comment] 2021-01-21 17:42
Hello and thank you for this return.
You should now be able to configure Mollie module.

I can understand your reply that cancelllation of orders is not due to Mollie. Please let me explain the context and I hope it will be clearer. The fact is that between 17 :30pm to 9 :15am today, no payment with Mollie was available. During this time, many clients had been trying to pay with Mollie. Because it didn't work, they paid with other independant methods like bankwire and Paypal. And these bankwire and paypal orders have been automatically cancelled some minutes later. Which has never happened for years. And since the mollie upgrade this morning, everything has been fine...
So I searched for details into log files, Mollie dashboard, and Prestashop BO. Here is my analysis.

Example order 80408 ref FUSSEHUAT. 

1. Paid with Mollie at 00:28. On Mollie dashboard we can see it, dated at that time. In log file :[21/Jan/2021:00:28:30 +0100] "GET /fr/module/mollie/ajax?ajax=1&action=getTotalCartPrice HTTP/1.1" 200 515
2. But it fails, error 500.  log: [21/Jan/2021:00:28:41 +0100] "POST /fr/module/mollie/payment?method=creditcard HTTP/1.1" **500** 9476
3. The user tried to pay by bankwire at 0:32. [21/Jan/2021:00:32:18 +0100] "POST /fr/module/ps_wirepayment/validation HTTP/1.1" 302 
4. Order #80408 is created on Prestashop. log [21/Jan/2021:00:32:19 +0100] "GET /fr/index.php?controller=order-confirmation?id_cart=216030&id_module=30&id_order=80408
![image](https://user-images.githubusercontent.com/10560114/105388552-14ecd280-5c17-11eb-8624-b702d3bd78b6.png)

3. The order is automatically cancelled at 00:46, which is the time of "expired" on Mollie dashboard. In the log we can see [21/Jan/2021:00:46:04 +0100] "POST /fr/module/mollie/**webhook** HTTP/1.1" 200 7482 "-" "Mollie HTTP client/1.0"
On Mollie dashboard page, this is the time of expiration : 
![image](https://user-images.githubusercontent.com/10560114/105387245-a2c7be00-5c15-11eb-8b0e-10156e792633.png)
In PS BO : 
![image](https://user-images.githubusercontent.com/10560114/105389363-0bb03580-5c18-11eb-885f-5a42b4adef3a.png)

So in a certain way, we can say that Mollie has cancelled orders paid with a second method (paypal or bankwire).
It is the consequence of the Mollie failure (eror 500). I don't know if it can be reproduced, but at least this is the explanation.

Thanks and regards
Denis

**Comment by Saimis777** [comment] 2021-01-22 08:28
Hello @Ditwo , thank you for your analysis, it's definitely helpful!

Could you also clarify if granting further permissions is an issue or not? As we can't check Mollie settings due to a lack of permissions.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by Ditwo** [comment] 2021-01-22 08:51
Hello,
I extended the authorisations yesterday and I've just checked now. It's OK.
Could you try again?
Yours sincerely
Denis

**Comment by Saimis777** [comment] 2021-01-22 15:13
@Ditwo yes, once the developers going to look it over, I will get back to you!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-02 11:36
Hello @Ditwo,

Have you managed to try out the new version, and clarify if the issue persists? 

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by Ditwo** [comment] 2021-02-02 12:21
Hello,
Yes I installed it last friday. There is no error 500 anymore. So it's fine ;)
Except there are split orders sometimes, but doesn't seem to be related to Mollie.
Best regards,
Denis

**Comment by Saimis777** [comment] 2021-02-02 12:30
Nice, glad that it's good now!

I will close this issue for now, if you will encounter any further errors, please let me know!

--
Best regards,
Invertus Support team

**Closed by Saimis777** 2021-02-02 12:30 UTC
