### ISSUE TITLE
error when upgrading from 4.2.2 to 4.2.4 or to 4.3.0

### ISSUE THREAD

**Issue by Ditwo** [mollie/PrestaShop#363] opened 2021-06-24 07:16 UTC
Hello, 
Please find below details of an ennoying issue which occurs when upgrading the moudl. 
Thank you very much for your help
Denis

### Expected behavior

possibility to upgrade from 4.2.2 to 4.2.4 or to 4.3

### Actual behavior

error when upgrading : "Failed to parse dotenv file due to unexpected whitespace" in modules/mollie/vendor/vlucas/phpdotenv/src/Parser.php at line 163

### Steps to reproduce the behavior

click "upgrade" button, or add a new module and download it
![Capture-mollie-4 2 4](https://user-images.githubusercontent.com/10560114/123218938-9d281a00-d4cc-11eb-9d7b-0f5a2d522863.JPG)

### Environment
* PrestaShop version: 1.7.6.5 
* Mollie module version: 4.2.2 
* PHP version: 7.2.34

**Comment by Saimis777** [comment] 2021-06-25 11:47
Hi @Ditwo ,

How are you?

Did you try to reset the module? Does it show the same after a reset?

--
Best regards,
Invertus Support team

**Comment by Ditwo** [comment] 2021-06-25 14:22
Hello,

 

Thank you for your answer. As the site was broken, I returned to 4.2.2 and didn’t want to reproduce that L

So I was waiting for your analysis. Have you an idea of the cause of the error ? I noticed the file .env.dist is different in 4.2.4. Maybe the cause. What do you think ?

 

Best regards

Denis 

 

De : Saimis777 ***@***.*** 
Envoyé : vendredi 25 juin 2021 13:48
À : mollie/PrestaShop
Cc : Ditwo; Mention
Objet : Re: [mollie/PrestaShop] error when upgrading from 4.2.2 to 4.2.4 or to 4.3.0 (#363)

 

Hi @Ditwo <https://github.com/Ditwo>  ,

How are you?

Did you try to reset the module? Does it show the same after a reset?

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-06-28 12:05
Hey @Ditwo ,

I've forwarded the information to the developer, they will take a closer look, and I will let you know!

Thank you for your patience.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-06-29 09:37
Hey @Ditwo ,

Maybe you could provide us with your BO+FTP credentials to - support@invertus.eu for further investigation? As I could not reproduce the issue, would need to take a look at your shop. 

Also would you give us permission to try to re-install the module on your shop?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-07-01 06:43
Hi again @Ditwo ,

Will you be able to provide the credentials for the shop for further investigation?

Let me know!

Have a nice day.

--
Best regards,
Invertus Support team

**Comment by Ditwo** [comment] 2021-07-01 06:44
Hello,

 

Thank you for your return. 

 

Just to come back to the context, the issue occurs when upgarding from 4.2.2 to 4.2.4 (version available on Prestashop Addons). 

It leads to an error 500 :

error when upgrading : "Failed to parse dotenv file due to unexpected whitespace" in modules/mollie/vendor/vlucas/phpdotenv/src/Parser.php at line 163

 

According to me, the reason is nested in the file .env.dist of the 4.2.4 version with that content :

MARKETPLACE=module from marketplace

The error is reported like below, and we can see ‘module from market place’ outlined :



 

 

In 4.2.2 and 4.3.0, the .env.dist file is the same, but doesn’t have the same content as in 4.2.4 : 

#DEV=development

#TEST=test shop

#PRE_PROD=preprod shop

#GITHUB=module from github

#MARKETPLACE=module from marketplace

SENTRY_ENV='GITHUB'

 

We can see that the line is now commented with # :

#MARKETPLACE=module from marketplace

 

I really don’t know why the .env.dist has changed from 4.2.2 to 4.2.4. However, this causes the error.

 

 

I’ve just upgraded from 4.2.2 to 4.3.0 and it works like a charm.

The pity is that on Prestashop Addons the version available is still 4.2.4, which contains that issue in .env.dist file.

 

 

Best regards

Denis 

 

De : Saimis777 ***@***.*** 
Envoyé : mardi 29 juin 2021 11:38
À : mollie/PrestaShop
Cc : Ditwo; Mention
Objet : Re: [mollie/PrestaShop] error when upgrading from 4.2.2 to 4.2.4 or to 4.3.0 (#363)

 

Hey @Ditwo <https://github.com/Ditwo>  ,

Maybe you could provide us with your BO+FTP credentials to - ***@***.*** for further investigation? As I could not reproduce the issue, would need to take a look at your shop.

Also would you give us permission to try to re-install the module on your shop?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Ditwo** [comment] 2021-07-01 07:05
Hello Team,

 

I guess there is no need to investigate further as the module has been correctly migrated to version 4.3.0. As I reported, the error was in the .env.dist file in version 4.2.4. I recommend you to change this version on Prestashop Addons and replace it with version 4.3.0.

 

Best regards

Denis 

 

De : Saimis777 ***@***.*** 
Envoyé : jeudi 1 juillet 2021 08:43
À : mollie/PrestaShop
Cc : Ditwo; Mention
Objet : Re: [mollie/PrestaShop] error when upgrading from 4.2.2 to 4.2.4 or to 4.3.0 (#363)

 

Hi again @Ditwo <https://github.com/Ditwo>  ,

Will you be able to provide the credentials for the shop for further investigation?

Let me know!

Have a nice day.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-07-01 08:40
Hey @Ditwo ,

We really appreciate your time and effort regarding this feedback, thank you!

The issue is identified, and will be either fixed or a new version released.

I will close this issue for now, if you'll need further help with this or anything else, feel free to re-open the issue or raise a new one!

Have a nice day!

--
Best regards,
Invertus Support team

**Closed by Saimis777** 2021-07-01 08:40 UTC
Labels: Status: Additional Info Required, Type: Support

**Comment by Ditwo** [comment] 2023-12-29 11:48
Hello,

Since 27/12 at 21h56, we have had the problem as described in the subject line. It appears on about one order out of ten, with different carriers. For the record, we didn't change anything on the site.
A priori there is no double debit from the customer in mollie account. In Prestashop order page, there is an error : Warning, paid 200€ instead of 100€ (for example).

The version of the Mollie module is 6.0.4, prestashop 1.7.6.5.
Thank you for your help in this matter. 
I’m at your disposal to give you more details.

Best regards
Denis

**Comment by justelis22** [comment] 2024-01-02 08:31
@Ditwo Hi there,

I replied to you on the addons marketplace, let's keep the communication there, as this is an unrelated and old GitHub issue.

--
Best regards,
Invertus Support team
