### ISSUE TITLE
Orderconfirmation email does not display name

### ISSUE THREAD

**Issue by MariannevdS** [mollie/PrestaShop#289] opened 2021-01-30 10:16 UTC
### Expected behavior
The email to the backoffice new_order should display firstname lastname and email.

### Actual behavior
fields remain empty, in the template the {firstname}{lastname} etc are correct and not changed; In the onder_conf email to client also the name is not displayed

### Steps to reproduce the behavior
![Schermafbeelding 2021-01-30 om 09 53 39](https://user-images.githubusercontent.com/78209224/106353678-8a7a3200-62ec-11eb-81f8-d9a04a6765d7.jpg)
When client makes new order, email is sent in this way 

### Environment
* PrestaShop version: 1.7.7.1 
* Mollie module version: 4.2.1 
* PHP version: 7.1.34

**Comment by pic16f876** [comment] 2021-01-30 10:52
I have the same issue.
Presta 1.7.6.5
Mollie 4.2
No multistore

**Comment by Maz-Invertus** [comment] 2021-01-30 11:02
Hi @pic16f876!

Thank you for being active community member. Have you tried the 4.2.1 version?

--
Best regards,
Invertus Support team

**Comment by pic16f876** [comment] 2021-01-30 11:26
No @Maz-Invertus I have not since its quite a bit of work updating. IT is not as easy as hitting the update button. I have to completely remove and reconfigure the module with every little update or I get 500 errors.. do I ususally wait a bit. Will try next week and give an update.

**Comment by Saimis777** [comment] 2021-02-01 14:54
@MariannevdS thank you for your message,

We've registered the issue, will try to reproduce it, and see what we can do!

And @pic16f876 thank you as well, we will be waiting for your update as well!

--
Best regards,
Invertus Support team

**Comment by imagicuus** [comment] 2021-02-03 15:59
I have the same issue for a while: https://github.com/mollie/PrestaShop/issues/247

**Comment by Saimis777** [comment] 2021-02-05 09:55
Hello @imagicuus,

Thank you for your report, we're still investigating this issue, I will keep you posted.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-05 14:17
Hello everyone,

We've managed to resolve the issue, and included it in the 4.2.2 release, which we are planning to release next week (if nothing goes wrong), it will be uploaded here - https://github.com/mollie/Prestashop/releases

Be sure to follow the link where the latest version will be updated!

I will close this issue for now, if this will persist after the new release, just let me know!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-08 14:41
Hello @pic16f876,

Have you managed to retry installing the module? How did it went? Did you encounter any further errors?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by pic16f876** [comment] 2021-02-08 14:58
Hi,

Yes I did install it but it was the same result. Since you said it would be fixed next release I did not update.

**Comment by Saimis777** [comment] 2021-02-09 13:21
@pic16f876 Hello,

Understood, just wanted to clarify if you've tried it from your end, as any feedback is greatly appreciated!

Thank you for the reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-11 09:42
Hello @MariannevdS @pic16f876  @imagicuus , hope you're having a nice day so far!

We've just launched the 4.2.2 Mollie version, maybe you could try and install it, and provide any feedback regarding the new version?

You can download the latest version here - https://github.com/mollie/Prestashop/releases

As we did multiple checkouts and testing, no Order Confirmation display text issues on PS1771 PHP 7.2. seem to be found.

Looking forward to your feedback!

--
Best regards,
Invertus Support team

**Comment by petrovv77** [comment] 2021-02-11 18:44
I have updated the module to 4.2.2. 
The customer names are now displayed, but not yet the list of purchased products  #283.

**Comment by Saimis777** [comment] 2021-02-12 14:47
Thank you for reporting that @petrovv77 !

We are checking the issue further!

--
Best regards,
Invertus Support team

**Comment by MariannevdS** [comment] 2021-02-16 13:17
Hello,
Thank you for the update!
The names and emailadres are good now.
One thing that this update did not fix for me is applePay. I read that this is fixed for the 1.6 version, but it is also a problem in the 1.7.7 Prestashop. I have Apple Pay active in BO but it does not show up at front.

**Comment by Saimis777** [comment] 2021-02-17 09:55
Hello @MariannevdS thank you for reporting that!

Maybe you could raise a separate issue regarding the Apple Pay method, describe the issue further, so we could investigate it more throughly?

--
Best regards,
Invertus Support team

**Comment by MariannevdS** [comment] 2021-02-17 10:13
I can do that, it was reported earlier in this topic too: https://github.com/mollie/PrestaShop/issues/275#issuecomment-770178767

**Comment by Saimis777** [comment] 2021-02-18 07:53
@MariannevdS ,

Would be great if you could raise a new issue, describe your environment, and we could see maybe other users are encountering this as well!

Please let me know if you will be able to do that!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-18 07:56
Also @MariannevdS ,

Could you maybe check this page - https://applepaydemo.apple.com/ and screenshot what does it show for you in the grey box?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-18 09:20
@MariannevdS,

Sorry for the spamming, but I've created the issue for you, maybe you could just clarify the details (environment, steps of issue reproduction)?

The issue link - https://github.com/mollie/PrestaShop/issues/295

--
Best regards,
Invertus Support team

**Comment by pic16f876** [comment] 2021-02-18 14:12
I Installed the module update today. Test order seems okay, will update later if another problem should arise.

**Comment by Saimis777** [comment] 2021-02-18 15:03
Hello @pic16f876,

Thank you for your feedback! Definitely keep us posted if you will notice anything regarding the module, your feedback is greatly appreciated!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-02-22 16:36
Hello @pic16f876 ,

Have you noticed anything else or maybe you have more feedback regarding the module?

Or we can close this issue?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by MariannevdS** [comment] 2021-02-22 16:49
Names and all are good, no more issues besides the one which is new issue apple-pay

**Comment by pic16f876** [comment] 2021-02-22 17:08
@Saimis777 for me this issue is resolved. Was also able to update the module in stead of completely deinstalling first so all is well on my side.

**Comment by Saimis777** [comment] 2021-02-23 08:43
Hey @MariannevdS @pic16f876 ,

Thank you for the clarifications, glad everything works! I will close this issue for now, as it's a confirmed fix.

@MariannevdS Regarding Apple pay, I've followed up with a details request for further investigation on https://github.com/mollie/PrestaShop/issues/295 if you could please clarify the details, we could then continue on with the investigation!

And let me know if you need further assistance regarding this case.

--
Best regards,
Invertus Support team

**Closed by Saimis777** 2021-02-23 08:43 UTC
