### ISSUE TITLE
Total_paid_real is not empty even when order is not completed.

### ISSUE THREAD

**Issue by Maikel726** [mollie/PrestaShop#309] opened 2021-04-01 10:15 UTC
### Expected behavior
Total_paid_real line should be empty or 0.0000 when an order is not completed.

### Actual behavior
Total_paid_real contains the total value of the order.

### Steps to reproduce the behavior
Order an test order and do not complete the order by paying, total_paid_real should be filled in then with the total order amount.

### Environment
* PrestaShop version: 1.7.6.9
* Mollie module version: 4.2.3
* PHP version: 7.2.34

**Comment by Saimis777** [comment] 2021-04-01 14:11
Hello @Maikel726 ,

Thank you for the message!

We'll try to replicate this issue, and I will get back to you as soon as possible!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-04-06 09:26
Hello @Maikel726 ,

Just wanted to inform you that we are still working on the case, I am waiting for further feedback from the development team.

Thank you for your patience.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-04-08 13:51
Hello @Maikel726 ,

We've managed to resolve the issue, and going to include the fix in the next release! Now the total_paid_real will be set when we get the status paid from Mollie.

I will let you know once I will know the confirmed date of the realase.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-04-21 14:42
Hello,

A new version of Mollie was just released, with a fix included, you can download the latest version here - https://github.com/mollie/PrestaShop/releases/tag/4.2.4

We are closing this issue for now, if the issue is still there be sure to let us know, we'll reopen the issue!

And be sure to provide us feedback regarding the latest release!

--
Best regards,
Invertus Support team

**Closed by Saimis777** 2021-04-21 14:42 UTC
Labels: Priority: Medium, Release: Upcoming release, Status:  In Progress, Type: Bug
