### ISSUE TITLE
Confirmation page after paiment

### ISSUE THREAD

**Issue by Nux007** [mollie/PrestaShop#787] opened 2023-08-22 09:28 UTC
### Expected behavior
Display the order information after the payment was processed.

### Actual behavior
As the screenshot below, no information is shown to the customer after succes redirection.

![image](https://github.com/mollie/PrestaShop/assets/17247565/470a895d-b09c-4226-ba70-fd34254e9da5)

### Environment
* PrestaShop version: 1.7.8.5
* Mollie module version: 6.0.2
* PHP version: 7.4.28

**Comment by Nux007** [comment] 2023-08-23 13:07
There is no error message in dev console, but in the prestashop logs I can find this:

![image](https://github.com/mollie/PrestaShop/assets/17247565/6d7cca9d-3d22-4ccc-b48a-d4fbe8c95bf9)

All other paiments methods was working (Stripe, MoneyTigo, ...).

**Comment by Nux007** [comment] 2023-08-25 11:47
Hello, any news about this ?

**Comment by justelis22** [comment] 2023-08-28 05:33
Hi @Nux007,

We have analyzed the issue, however, we could not recreate it from our side with the default PrestaShop environment.
Most likely it is related to your theme or 3rd party modules. 
Perhaps you have a development environment where you could turn off some of the modules and change the theme to the default one to identify the root cause.

Best Regards,
Invertus Support team.

**Comment by Nux007** [comment] 2023-08-28 05:35
I can't do that I do not have all code on my hand. We never had this issue with all paiment methods we used before. My fix will be to go back to Stripe :(

**Comment by justelis22** [comment] 2023-08-28 06:58
@Nux007,

In that case, would it be possible for you to share back office and FTP credentials with us via email - support@invertus.eu?
Also if you could share the whole backup including the database, it would be even better, in that case, I could deploy your shop locally and debug from my side.

Best Regards,
Invertus Support team.

**Comment by Nux007** [comment] 2023-08-29 10:14
Hello @justelis22 I tested to reproduce this bug from an other client website and it sounds like I cannot reproduce it on this one... So, as you said, it's related to the shop theme. Unfortunately, I can't share the whole website for privacy reasons :(

**Comment by Nux007** [comment] 2023-08-29 13:47
Invastigating a bit more to find out how to fix this, I can see the transaction_id is not registered into the mollie_payment table when thjis bug appens 

![image](https://github.com/mollie/PrestaShop/assets/17247565/a6d4ed5f-070d-4549-8c8b-2de714ec4a55)

But the paiment was made
![image](https://github.com/mollie/PrestaShop/assets/17247565/5f99aa1f-c9a9-425c-9ab9-c4543b153c3a)

**Comment by justelis22** [comment] 2023-08-31 08:21
@Nux007 Hello there,

Perhaps it would be possible to share the theme files so that we could test with the theme only to identify the issue?

Best Regards,
Invertus Support team.

**Comment by wzzly** [comment] 2023-09-06 07:30
@justelis22  I have the exact same problem after updating PS to 1.7.8.10 
Mollie 6.0.3
After an order is paid, I get a page with: Er bestaat geen bestelling met deze ID.
"No order exists with this ID"
The order does exist in BO and is PAID.
This is a real problem as now no orders are being tracked by Google Ads, because this happens on the order confirmation page. Please investigate ASAP.
It only happens when an order is paid with Mollie. All other payment methods redirect to confirmation page after payment.
This is in PS log:
![image](https://github.com/mollie/PrestaShop/assets/35727938/1dbc79a1-75f2-4d7f-bd8f-30a7cbf60a7b)

There are no server errors.

**Comment by ausrinekr** [comment] 2023-09-06 11:24
Hi there @wzzly ,

Thank you for the sent copy of the website on a subdomain, however, if no errors persist in logs or browser console we cannot really check much.

Could you please share the whole backup including the database via email? We could deploy your shop locally and debug it from our side.

Best Regards,
Invertus Support team.

**Comment by mandan2** [comment] 2023-09-11 13:50
Hello @wzzly  ,

We have just checked your sent shop. Issue seems to persist due to missing "mandate_id" column in mollie_payments table. Try to launch following SQL query for your test shop and try to do some test orders to verify if suggestion fixes your problem.

`ALTER TABLE pr_mollie_payments ADD mandate_id VARCHAR(64);`

Best Regards,
Invertus Support team.

**Comment by mandan2** [comment] 2023-09-11 14:11
Hello @Nux007 ,

Could you give us some more context. Is order being finished or cart is still full of products? If order is finished, is order status changed to anything than "Awaiting payment"? Furthermore, is Mollie payment reference being updated to PrestaShop order reference in Mollie dashboard? Lastly, is order from "mollie_payments" table being updated with order_id, bank_status, transaction_id?

If no order is created in PrestaShop, could you check if our message above covers your case as well with missing mandate_id? 

Best Regards,
Invertus Support team.

**Comment by Nux007** [comment] 2023-09-12 10:11
Hello @mandan2 
The order is completed and all payment information are stored into the prestashop payment but not into the mollie payment table. The payment status is correctly set to the correct one. In fact, **ALL** is good except that the payment is not registered into the mollie table as shown in my previous screenshot.

Here is a screen of my mollie_payment table:

![image](https://github.com/mollie/PrestaShop/assets/17247565/4b83642b-4284-4978-85fe-354c70b67846)

**Comment by Nux007** [comment] 2023-09-19 12:42
Hello @mandan2 I confirm that that's fixing the bug :-)

Thanks.

**Comment by justelis22** [comment] 2023-09-20 05:59
Hello @Nux007,
Glad to hear that!

Is everything fine now? Perhaps we can close this issue?

Best Regards,
Invertus Support team.

**Closed** 2023-09-20 07:32 UTC
