### ISSUE TITLE
4.3.3 : no payment available anymore

### ISSUE THREAD

**Issue by Ditwo** [mollie/PrestaShop#402] opened 2021-09-07 06:42 UTC
Hello,
Since we have upgraded to 4.3.3, customers can't place an order, as there is no more payment method available. Thank you for your help.
Best regards

### Expected behavior
get as before the update all the payment methods like bankwire, ...

### Actual behavior
Since the upgrade to 4.3.3, no payment methods available

### Steps to reproduce the behavior
Upgrade the module to 4.3.3

### Environment
* PrestaShop version: 1.7.6.8, or 1.7.7.7
* Mollie module version: 4.3.3
* PHP version: 7.3

**Comment by Saimis777** [comment] 2021-09-07 07:19
Hi @Ditwo ,

Thank you for your message.

Could you clarify where exactly you can't see the payment methods? Are they not showing in the front office? Or in the Mollie module itself? Have you tried checking this guide out here - https://github.com/mollie/PrestaShop/wiki/Troubleshooting#payment-method-does-not-appear-in-front-office ?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Ditwo** [comment] 2021-09-07 07:34
Hello Team,

Thanks for your reply. Actually I meant that in Front Office, when checking out, there is no method anymore, even those that have nothing to see with Mollie, like bankwire.
With Mollie 4.3.3 deactivated, you can see Paypal and bankwire :
![Capture0](https://user-images.githubusercontent.com/10560114/132302657-71d5ea9c-5695-4f84-8933-a01a221632c0.JPG)
With Mollie 4.3.3 **activated**, no payment methods anymore :
![Capture](https://user-images.githubusercontent.com/10560114/132302763-ffd96352-c949-423a-b148-bd8f988e3ec0.jpg)

And when I **reinstall 4.3.2**, it works again : 
![Capture-4 3 2](https://user-images.githubusercontent.com/10560114/132303426-b9168518-398c-4fb9-afdc-709724252473.JPG)

--> it happens on 2 differents sites. I think it is due to the 4.3.3 release.
Thank you for your help,
Denis

**Comment by Saimis777** [comment] 2021-09-07 07:38
Thanks for the clarification.

As I can see the guide should help you resolve the issue - https://github.com/mollie/PrestaShop/wiki/Troubleshooting#payment-method-does-not-appear-in-front-office

Please follow all the steps, as we did not encounter any bugs on this release that might block the payment methods.

--
Best regards,
Invertus Support team

**Comment by Ditwo** [comment] 2021-09-07 08:17
Hello,
I followed these steps but the issue is still there.  Anyway I'm not surprised because the wiki deals with Mollie payments, and not the other payments like bankwire and paypal.
What can I do ?

**Comment by Saimis777** [comment] 2021-09-08 07:57
Hi,

We would need your back office + FTP credentials sent to - support@invertus.eu for further investigation, if the guide did not help.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by ber-nie** [comment] 2021-09-14 07:24
Hello Ditwo, hello Saimis777,

I have the same problem:

    PrestaShop version: 1.7.7.7
    Mollie module version: 4.3.3
    PHP version: 7.3

Since the upgrade of Mollie module to 4.3.3, no payment methods available.

Have you already found a solution for the problem?

Best regards,
Bernhard

**Comment by Saimis777** [comment] 2021-09-14 08:45
Hi @ber-nie ,

We could not reproduce the issue on our end, with a default install, therefore asked for credentials to check, but have yet to receive them.

Did the wiki steps not helped you as well? 

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by waschier-design** [comment] 2021-09-14 11:17
Same Error here.
Payment Methods do not show in Frontoffice.

PS: 1.7.7.4
Mollie Version 4.3.3
PHP Version: 7.2.34

**Comment by Saimis777** [comment] 2021-09-14 13:16
Hi @waschier-design ,

Maybe you could provide us with your BO + FTP credentials to - support@invertus.eu for further investigation please?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by ber-nie** [comment] 2021-09-14 15:31
Thank you, @Saimis777.
This is also the solution for me. 
Mollie-Payment works again after changing the language-code from "de" to "de-de".

**Comment by Saimis777** [comment] 2021-09-15 06:18
Thank you for the clarification @ber-nie ,

Since the issue is resolved for everyone, I am closing it for now.

Let me know if you have any other questions!

--
Best regards,
Invertus Support team

**Closed by Saimis777** 2021-09-15 06:18 UTC
Labels: Priority: Low, Type: Support
