### ISSUE TITLE
Payments are always registered double

### ISSUE THREAD

**Issue by 7GRAFIX** [mollie/Prestashop#38] opened 2017-05-27 20:25 UTC
Hello

For some strange reason, all payments are always registered double on the orders page. 
In the example below, the order amount was 199,99 EUR, but it says 399,98 € was paid which is not true. 
The client paid 199,99 EUR via Mollie (payment method Mistercash). 
I also double check if it's a certain method, but no it happens with all of them. 
Except in some cases there is no method available. Also very strange. (example in attachment too)

Did somebody encounter this issue too? Any ideas or fixes to get rid of this annoying issue? 
Does it has anything to do with the order status that might register a payment double? 
I enclose a screenshot from the settings if anybody needs to see it. 

Please let me know if this is a known (new) issue or if we are using some kind of wrong parameter or configuration, but I can not see anything wrong in the configuration section. 

Thanks!

<img width="982" alt="schermafdruk 2017-05-27 22 16 39" src="https://cloud.githubusercontent.com/assets/7568546/26524142/43fb455c-432a-11e7-8d3b-26b71f5707dc.png">
<img width="973" alt="schermafdruk 2017-05-27 22 16 33" src="https://cloud.githubusercontent.com/assets/7568546/26524143/43fd84fc-432a-11e7-8a3a-d52465efebf2.png">
<img width="954" alt="schermafdruk 2017-05-27 22 20 47" src="https://cloud.githubusercontent.com/assets/7568546/26524165/ca8e65d6-432a-11e7-9936-95cc4f35062e.png">
<img width="737" alt="schermafdruk 2017-05-27 22 24 01" src="https://cloud.githubusercontent.com/assets/7568546/26524182/4ba92e30-432b-11e7-87c9-7c03805078b4.png">

**Comment by 7GRAFIX** [comment] 2017-06-06 20:32
Hello, anybody alive here?

**Comment by tomasmollie** [comment] 2017-06-07 15:21
Hi @7GRAFIX,

We are currently investigating this with our Prestashop partner and will let you know as soon as we can provide you with an update. For now, apologies for the issues and delay.

**Comment by Trendweb** [comment] 2017-06-18 04:22
Hello @7GRAFIX,

Could you please let us know if you still need support? Otherwise, we have to close the issue.

Regards

**Comment by 7GRAFIX** [comment] 2017-06-18 10:56
Hello,

Sorry for late reply. 
We are running version 1.6.1.6. and mollie version 1.3.0 with below server details. 

Servergegevens Linux #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64
Server softwareversie nginx/1.10.3
PHP versie 7.0.9
Geheugenlimiet 512M
Maximale uitvoeringstijd 3000
MySQL versie 10.0.30-MariaDB-0+deb8u2

Is that Mollie version you sent newer than the one we already using?

**Comment by Trendweb** [comment] 2017-06-18 11:41
Hi @7GRAFIX ,

The plugin I sent is only compatible with Prestashop 1.7 and up. I sent it because your problem, as described, is a know problem in Prestashop 1.7. It's not compatible with Prestashop 1.6. 

I see you are using PHP 7.0.9. Is it possible to lower your PHP version to version 5.6.x (or lower, minimum version: 5.2) and do a test payment to see if the problem still occurs? PHP 7.0.x is known to cause problems because it contains bugs, so this could be the cause of your problem as well. 

You can also disable your other (paid) Modules (the ones which you have added afterwards and which are not standard) and keep the Mollie Module enabled. Do a test payment to see if one of your other modules is conflicting with the Mollie Module.

Regards

**Comment by Trendweb** [comment] 2017-06-30 05:47
Hi @7GRAFIX ,

Have you had a chance to try our suggestions? Please let us know so we can solve this problem.

Regards

**Comment by Trendweb** [comment] 2017-07-12 06:53
Hi @7GRAFIX ,

We are closing this issue. You can still place comments to let us know if you still need support. We will close comments after 1 week.

Regards

**Closed by Trendweb** 2017-07-12 06:53 UTC

**Comment by 7GRAFIX** [comment] 2017-07-12 06:59
@Trendweb 
Sorry, I just saw this message. I changed recently company name and domain. 
We have changed PHP to 5.6 and are still investigating the issue. 
There is/was also an issue with another module - EffectConnect - to sync product data with Bol.com plaza which also conflicted due it's own payment settings. 
We have disabled this plugin too and we are now monitoring all activity and orders to see if the issue is solved permanently.

**Comment by Trendweb** [comment] 2017-07-12 07:10
Hi @7GRAFIX ,

Thank you for informing us. Please let us know if the issue has been solved perminently, if not, we will offer you further support to resolve this. Just a suggestion, are you currently using a "clean URL module" to remove ID numbers from the URL's? Some of these cause problems with other modules. Perhaps this could be (part of) the problem as well.

Regards

**Comment by 7GRAFIX** [comment] 2017-07-15 11:19
@Trendweb 

We have been debugging for the past days but the problem is not solved. 
Payments are still being registered double. 

We are running PHP 5.6 now for 2 weeks. 
EffectConnect has been disabled the whole week and still not solved. 
We are not using any modules that touch the URL or permalinks. 

Any other suggestions that might cause this? 

<img width="962" alt="schermafbeelding 2017-07-15 om 13 15 35" src="https://user-images.githubusercontent.com/7568546/28238955-03d3b20a-6960-11e7-9e80-ce2d9679d1f2.png">

**Comment by Trendweb** [comment] 2017-07-15 13:07
Hi @7GRAFIX ,

Can you please contact me at info@trendweb.nl . To solve this, we will have to debug ourselves / recreate the error so we can find out what is causing the problem.

Regards

**Comment by emestels** [comment] 2018-01-15 16:01
Hello,
I have the same issue, payments are registered 3 times in prestashop!
I'm using v1.3.1 (still noticed as 1.3.0), in test mode, on a production website as I'm new to mollie.
how can I fix the issue.
Prestashop version is 1.6.1.11
on following server config:
Informations sur votre serveur Linux #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64
Version du logiciel serveur Apache/2.4.25 (Debian)
Version de PHP 7.0.27-0+deb9u1 

Thanks in advance for your help.
Regards

**Comment by Trendweb** [comment] 2018-01-15 16:27
Hi @emestels ,

We are Mollie's Prestashop partner. Could you please contact us at info@trendweb.nl? We will gladly help you out on solving this problem.

Kind Regards
