### ISSUE TITLE
Creditcard payments VAT problem for B2B orders when Mollie Components enabled.

### ISSUE THREAD

**Issue by BricksDirect** [mollie/PrestaShop#282] opened 2021-01-21 11:37 UTC
### Expected behavior
For B2B orders the VAT should be remitted when buyer provides a valid VAT ID.

### Actual behavior
This is working for all payment methods, but not for creditcards when Mollie components is enabled.
When Mollie components is disabled it works fine and there is no VAT charged.
When Mollie components is enabled it doesn't work and VAT is charged.

### Steps to reproduce the behavior
Enable Mollie components and try to place an order with valid VAT id.
You will see that VAT is charged by the Mollie Module.

### Environment
* PrestaShop version: 1.7.6.9
* Mollie module version: 4.1.3
* PHP version: 7.2.34

**Comment by Saimis777** [comment] 2021-01-21 12:04
Hello @BricksDirect thanks for reporting your issue,

I will take a look with the team regarding your given steps to reproduce the issue, and will get back to you shortly, also is it the same with 4.2.0 Mollie version?

Best regards,
Invetus Support team

**Comment by Saimis777** [comment] 2021-01-21 15:02
@BricksDirect,

Could you also clarify if you are using any other modules that are removing VAT? If yes, could you clarify which one(s)?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by BricksDirect** [comment] 2021-01-21 17:02
Hello,

I don't know if this error occures with version 4.2.0. We have not yet updated to it because I saw there were some bugs in it.
Yes, we are using the European VAT number module.

Best regards,
Niels Roest
BricksDirect

**Comment by Saimis777** [comment] 2021-01-22 15:06
Hello @BricksDirect , thank you for the clarification.

Would it be possible to receive your front office/ back office / FTP details to - support@invertus.eu for further investigation? As the module European VAT is 70 euros, we would need to see how it works, and test it in your environment where the module is already installed.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by BricksDirect** [comment] 2021-01-22 20:06
Hello,

We have solved it now by disabling Mollie Components.
Sorry, we can't have errors on our site during your check.
It will cost our orders.

Best regards,
Niels Roest
BricksDirect

**Comment by Saimis777** [comment] 2021-01-25 07:58
@BricksDirect Thank you for your message,

Could you then clarify how should we proceed? As in order to troubleshoot this we would need to investigate your back office.

Should we then close the issue?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment] 2021-01-28 12:26
Hello @BricksDirect,

We are trying to replicate the issue from our end, yet with no success, the VAT number seems to be working, and when added a Belgium VAT number with a Belgium address, the price gets deducted (Mollie payments enabled), the theme was used as the default one, Prestashop version as the same one.

Maybe you could clarify how we can reproduce it? 

Looking forward to your reply!

Best regards,
Invertus Support team

**Closed** 2021-02-02 11:40 UTC
